6boris/awesome-golang-algorithm

leetcode/201-300/0238.Product-of-Array-Except-Self/README.md, leetcode/201-300/0238.Product-of-Array-Except-Self/Solution.go, leetcode/201-300/0238.Product-of-Array-Except-Self/Solution_test.go
Add solution and test-cases for problem 238
=> Add solution and test-cases for problem 238

leetcode/401-500/0405.Convert-a-Number-to-Hexadecimal/README.md, leetcode/401-500/0405.Convert-a-Number-to-Hexadecimal/Solution.go, leetcode/401-500/0405.Convert-a-Number-to-Hexadecimal/Solution_test.go
Add solution and test-cases for problem 405
=> Add solution and test-cases for problem 405

leetcode/601-700/0682.Baseball-Game/README.md, leetcode/601-700/0682.Baseball-Game/Solution.go, leetcode/601-700/0682.Baseball-Game/Solution_test.go
Add solution and test-cases for problem 682
=> Add solution and test-cases for problem 682

leetcode/1201-1300/1220.Count-Vowels-Permutation/README.md, leetcode/1201-1300/1220.Count-Vowels-Permutation/Solution.go, leetcode/1201-1300/1220.Count-Vowels-Permutation/Solution_test.go
Add solution and test-cases for problem  1220
=>  Add solution and test-cases for problem  1220

leetcode/2001-2100/2032.Two-Out-of-Three/README.md, leetcode/2001-2100/2032.Two-Out-of-Three/Solution.go, leetcode/2001-2100/2032.Two-Out-of-Three/Solution_test.go
Add solution and test-cases for problem 2032
=> Add solution and test-cases for problem 2032

leetcode/1201-1300/1237.Find-Positive-Integer-Solution-for-a-Given-Equation/README.md, leetcode/1201-1300/1237.Find-Positive-Integer-Solution-for-a-Given-Equation/Solution.go, leetcode/1201-1300/1237.Find-Positive-Integer-Solution-for-a-Given-Equation/Solution_test.go
Add solution and test-cases for problem 1237
=> Add solution and test-cases for problem 1237

leetcode/501-600/0539.Minimum-Time-Difference/README.md, leetcode/501-600/0539.Minimum-Time-Difference/Solution.go, leetcode/501-600/0539.Minimum-Time-Difference/Solution_test.go
Add solution and test-cases for problem 539
=> Add solution and test-cases for problem 539

leetcode/401-500/0436.Find-Right-Interval/README.md, leetcode/401-500/0436.Find-Right-Interval/Solution.go, leetcode/401-500/0436.Find-Right-Interval/Solution_test.go
Add solution and test-cases for problem 436
=> Add solution and test-cases for problem 436

leetcode/2101-2200/2149.Rearrange-Array-Elements-by-Sign/README.md, leetcode/2101-2200/2149.Rearrange-Array-Elements-by-Sign/Solution.go, leetcode/2101-2200/2149.Rearrange-Array-Elements-by-Sign/Solution_test.go
Add solution and test-cases for problem 2149
=> Add solution and test-cases for problem 2149

leetcode/801-900/0823.Binary-Trees-With-Factors/README.md, leetcode/801-900/0823.Binary-Trees-With-Factors/Solution.go, leetcode/801-900/0823.Binary-Trees-With-Factors/Solution_test.go
Add solution and test-cases for problem 823
=> Add solution and test-cases for problem 823

leetcode/1301-1400/1343.Number-of-Sub-arrays-of-Size-K-and-Average-Greater-than-or-Equal-to-Threshold/README.md, leetcode/1301-1400/1343.Number-of-Sub-arrays-of-Size-K-and-Average-Greater-than-or-Equal-to-Threshold/Solution.go, leetcode/1301-1400/1343.Number-of-Sub-arrays-of-Size-K-and-Average-Greater-than-or-Equal-to-Threshold/Solution_test.go
Add solution and test-cases for problem 1343
=> Add solution and test-cases for problem 1343

leetcode/901-1000/0991.Broken-Calculator/README.md, leetcode/901-1000/0991.Broken-Calculator/Solution.go, leetcode/901-1000/0991.Broken-Calculator/Solution_test.go
Add solution and test-cases for problem 991
=> Add solution and test-cases for problem 991

leetcode/1201-1300/1219.Path-with-Maximum-Gold/README.md, leetcode/1201-1300/1219.Path-with-Maximum-Gold/Solution.go, leetcode/1201-1300/1219.Path-with-Maximum-Gold/Solution_test.go
Add solution and test-cases for problem 1219
=> Add solution and test-cases for problem 1219

leetcode/2201-2300/2284.Sender-With-Largest-Word-Count/README.md, leetcode/2201-2300/2284.Sender-With-Largest-Word-Count/Solution.go, leetcode/2201-2300/2284.Sender-With-Largest-Word-Count/Solution_test.go
Add solution and test-cases for problem 2284
=> Add solution and test-cases for problem 2284

leetcode/1401-1500/1404.Number-of-Steps-to-Reduce-a-Number-in-Binary-Representation-to-One/README.md, leetcode/1401-1500/1404.Number-of-Steps-to-Reduce-a-Number-in-Binary-Representation-to-One/Solution.go, leetcode/1401-1500/1404.Number-of-Steps-to-Reduce-a-Number-in-Binary-Representation-to-One/Solution_test.go
Add solution and test-cases for problem 1404
=> Add solution and test-cases for problem 1404

leetcode/601-700/0641.Design-Circular-Deque/README.md, leetcode/601-700/0641.Design-Circular-Deque/Solution.go, leetcode/601-700/0641.Design-Circular-Deque/Solution_test.go
Add solution and test-cases for problem 641
=> Add solution and test-cases for problem 641

leetcode/301-400/0303.Range-Sum-Query--Immutable/README.md, leetcode/301-400/0303.Range-Sum-Query--Immutable/Solution.go, leetcode/301-400/0303.Range-Sum-Query--Immutable/Solution_test.go
Add solution and test-cases for problem 303
=> Add solution and test-cases for problem 303

leetcode/301-400/0354.Russian-Doll-Envelopes/README.md, leetcode/301-400/0354.Russian-Doll-Envelopes/Solution.go, leetcode/301-400/0354.Russian-Doll-Envelopes/Solution_test.go
Add solution and test-cases for problem 354
=> Add solution and test-cases for problem 354

leetcode/801-900/0813.Largest-Sum-of-Averages/README.md, leetcode/801-900/0813.Largest-Sum-of-Averages/Solution.go, leetcode/801-900/0813.Largest-Sum-of-Averages/Solution_test.go
Add solution and test-cases for problem 813
=> Add solution and test-cases for problem 813

leetcode/701-800/0788.Rotated-Digits/README.md, leetcode/701-800/0788.Rotated-Digits/Solution.go, leetcode/701-800/0788.Rotated-Digits/Solution_test.go
Add solution and test-cases for problem 788
=> Add solution and test-cases for problem 788

leetcode/1601-1700/1700.Number-of-Students-Unable-to-Eat-Lunch/README.md, leetcode/1601-1700/1700.Number-of-Students-Unable-to-Eat-Lunch/Solution.go, leetcode/1601-1700/1700.Number-of-Students-Unable-to-Eat-Lunch/Solution_test.go
Add solution and test-cases for problem 1700
=> Add solution and test-cases for problem 1700

leetcode/601-700/0678.Valid-Parenthesis-String/README.md, leetcode/601-700/0678.Valid-Parenthesis-String/Solution.go, leetcode/601-700/0678.Valid-Parenthesis-String/Solution_test.go
Add solution and test-cases for problem 678
=> Add solution and test-cases for problem 678

leetcode/701-800/0795.Number-of-Subarrays-with-Bounded-Maximum/README.md, leetcode/701-800/0795.Number-of-Subarrays-with-Bounded-Maximum/Solution.go, leetcode/701-800/0795.Number-of-Subarrays-with-Bounded-Maximum/Solution_test.go
Add solution and test-cases for problem 795
=> Add solution and test-cases for problem 795

leetcode/2901-3000/2958.Length-of-Longest-Subarray-With-at-Most-K-Frequency/README.md, leetcode/2901-3000/2958.Length-of-Longest-Subarray-With-at-Most-K-Frequency/Solution.go, leetcode/2901-3000/2958.Length-of-Longest-Subarray-With-at-Most-K-Frequency/Solution_test.go
Add solution and test-cases for problem 2958
=> Add solution and test-cases for problem 2958

leetcode/501-600/0592.Fraction-Addition-and-Subtraction/README.md, leetcode/501-600/0592.Fraction-Addition-and-Subtraction/Solution.go, leetcode/501-600/0592.Fraction-Addition-and-Subtraction/Solution_test.go
Add solution and test-cases for problem 592
=> Add solution and test-cases for problem 592

leetcode/1901-2000/1922.Count-Good-Numbers/README.md, leetcode/1901-2000/1922.Count-Good-Numbers/Solution.go, leetcode/1901-2000/1922.Count-Good-Numbers/Solution_test.go
Add solution and test-cases for problem 1922
=> Add solution and test-cases for problem 1922

leetcode/2701-2800/2799.Count-Complete-Subarrays-in-an-Array/README.md, leetcode/2701-2800/2799.Count-Complete-Subarrays-in-an-Array/Solution.go, leetcode/2701-2800/2799.Count-Complete-Subarrays-in-an-Array/Solution_test.go
Add solution and test-cases for problem 2799
=> Add solution and test-cases for problem 2799

leetcode/301-400/0330.Patching-Array/README.md, leetcode/301-400/0330.Patching-Array/Solution.go, leetcode/301-400/0330.Patching-Array/Solution_test.go
Add solution and test-cases for problem 330
=> Add solution and test-cases for problem 330

leetcode/1401-1500/1438.Longest-Continuous-Subarray-With-Absolute-Diff-Less-Than-or-Equal-to-Limit/README.md, leetcode/1401-1500/1438.Longest-Continuous-Subarray-With-Absolute-Diff-Less-Than-or-Equal-to-Limit/Solution.go, leetcode/1401-1500/1438.Longest-Continuous-Subarray-With-Absolute-Diff-Less-Than-or-Equal-to-Limit/Solution_test.go
Add solution and test-cases for problem 1438
=> Add solution and test-cases for problem 1438

leetcode/1001-1100/1052.Grumpy-Bookstore-Owner/README.md, leetcode/1001-1100/1052.Grumpy-Bookstore-Owner/Solution.go, leetcode/1001-1100/1052.Grumpy-Bookstore-Owner/Solution_test.go
Add solution and test-cases for problem 1052
=> Add solution and test-cases for problem 1052

leetcode/3001-3100/3039.Apply-Operations-to-Make-String-Empty/README.md, leetcode/3001-3100/3039.Apply-Operations-to-Make-String-Empty/Solution.go, leetcode/3001-3100/3039.Apply-Operations-to-Make-String-Empty/Solution_test.go
Add solution and test-cases for problem 3039
=> Add solution and test-cases for problem 3039

leetcode/801-900/0809.Expressive-Words/README.md, leetcode/801-900/0809.Expressive-Words/Solution.go, leetcode/801-900/0809.Expressive-Words/Solution_test.go
Add solution and test-cases for problem 809
=> Add solution and test-cases for problem 809

leetcode/901-1000/0911.Online-Election/README.md, leetcode/901-1000/0911.Online-Election/Solution.go, leetcode/901-1000/0911.Online-Election/Solution_test.go
Add solution and test-cases for problem 911
=> Add solution and test-cases for problem 911

leetcode/201-300/0220.Contains-Duplicate-III/README.md, leetcode/201-300/0220.Contains-Duplicate-III/Solution.go, leetcode/201-300/0220.Contains-Duplicate-III/Solution_test.go
Add solution and test-cases for problem 220
=> Add solution and test-cases for problem 220

leetcode/1601-1700/1653.Minimum-Deletions-to-Make-String-Balanced/README.md, leetcode/1601-1700/1653.Minimum-Deletions-to-Make-String-Balanced/Solution.go, leetcode/1601-1700/1653.Minimum-Deletions-to-Make-String-Balanced/Solution_test.go
Add solution and test-cases for problem 1653
=> Add solution and test-cases for problem 1653

leetcode/1601-1700/1605.Find-Valid-Matrix-Given-Row-and-Column-Sums/README.md, leetcode/1601-1700/1605.Find-Valid-Matrix-Given-Row-and-Column-Sums/Solution.go, leetcode/1601-1700/1605.Find-Valid-Matrix-Given-Row-and-Column-Sums/Solution_test.go
Add solution and test-cases for problem 1605
=> Add solution and test-cases for problem 1605

leetcode/1101-1200/1106.Parsing-A-Boolean-Expression/README.md, leetcode/1101-1200/1106.Parsing-A-Boolean-Expression/Solution.go, leetcode/1101-1200/1106.Parsing-A-Boolean-Expression/Solution_test.go
Add solution and test-cases for problem 1106
=> Add solution and test-cases for problem 1106

leetcode/701-800/0726.Number-of-Atoms/README.md, leetcode/701-800/0726.Number-of-Atoms/Solution.go, leetcode/701-800/0726.Number-of-Atoms/Solution_test.go
Add solution and test-cases for problem 726
=> Add solution and test-cases for problem 726

leetcode/1101-1200/1190.Reverse-Substrings-Between-Each-Pair-of-Parentheses/README.md, leetcode/1101-1200/1190.Reverse-Substrings-Between-Each-Pair-of-Parentheses/Solution.go, leetcode/1101-1200/1190.Reverse-Substrings-Between-Each-Pair-of-Parentheses/Solution_test.go
Add solution and test-cases for problem 1190
=> Add solution and test-cases for problem 1190

leetcode/1401-1500/1418.Display-Table-of-Food-Orders-in-a-Restaurant/README.md, leetcode/1401-1500/1418.Display-Table-of-Food-Orders-in-a-Restaurant/Solution.go, leetcode/1401-1500/1418.Display-Table-of-Food-Orders-in-a-Restaurant/Solution_test.go
Add solution and test-cases for problem 1418
=> Add solution and test-cases for problem 1418

leetcode/301-400/0350.Intersection-of-Two-Arrays-II/README.md, leetcode/301-400/0350.Intersection-of-Two-Arrays-II/Solution.go, leetcode/301-400/0350.Intersection-of-Two-Arrays-II/Solution_test.go
Add solution and test-cases for problem 350
=> Add solution and test-cases for problem 350

leetcode/1501-1600/1509.Minimum-Difference-Between-Largest-and-Smallest-Value-in-Three-Moves/README.md, leetcode/1501-1600/1509.Minimum-Difference-Between-Largest-and-Smallest-Value-in-Three-Moves/Solution.go, leetcode/1501-1600/1509.Minimum-Difference-Between-Largest-and-Smallest-Value-in-Three-Moves/Solution_test.go
Add solution and test-cases for problem 1509
=> Add solution and test-cases for problem 1509

leetcode/801-900/0831.Masking-Personal-Information/README.md, leetcode/801-900/0831.Masking-Personal-Information/Solution.go, leetcode/801-900/0831.Masking-Personal-Information/Solution_test.go
Add solution and test-cases for problem 831
=> Add solution and test-cases for problem 831

leetcode/801-900/0893.Groups-of-Special-Equivalent-Strings/README.md, leetcode/801-900/0893.Groups-of-Special-Equivalent-Strings/Solution.go, leetcode/801-900/0893.Groups-of-Special-Equivalent-Strings/Solution_test.go
Add solution and test-cases for problem 893
=> Add solution and test-cases for problem 893

leetcode/801-900/0884.Uncommon-Words-from-Two-Sentences/README.md, leetcode/801-900/0884.Uncommon-Words-from-Two-Sentences/Solution.go, leetcode/801-900/0884.Uncommon-Words-from-Two-Sentences/Solution_test.go
Add solution and test-cases for problem 884
=> Add solution and test-cases for problem 884

leetcode/1901-2000/1947.Maximum-Compatibility-Score-Sum/README.md, leetcode/1901-2000/1947.Maximum-Compatibility-Score-Sum/Solution.go, leetcode/1901-2000/1947.Maximum-Compatibility-Score-Sum/Solution_test.go
Add solution and test-cases for problem 1947
=> Add solution and test-cases for problem 1947

leetcode/1601-1700/1671.Minimum-Number-of-Removals-to-Make-Mountain-Array/README.md, leetcode/1601-1700/1671.Minimum-Number-of-Removals-to-Make-Mountain-Array/Solution.go, leetcode/1601-1700/1671.Minimum-Number-of-Removals-to-Make-Mountain-Array/Solution_test.go
Add solution and test-cases for problem 1671
=> Add solution and test-cases for problem 1671

leetcode/2501-2600/2501.Longest-Square-Streak-in-an-Array/README.md, leetcode/2501-2600/2501.Longest-Square-Streak-in-an-Array/Solution.go, leetcode/2501-2600/2501.Longest-Square-Streak-in-an-Array/Solution_test.go
Add solution and test-cases for problem 2501
=> Add solution and test-cases for problem 2501

leetcode/1001-1100/1006.Clumsy-Factorial/README.md, leetcode/1001-1100/1006.Clumsy-Factorial/Solution.go, leetcode/1001-1100/1006.Clumsy-Factorial/Solution_test.go
Add solution and test-cases for problem 1006
=> Add solution and test-cases for problem 1006

leetcode/2801-2900/2894.Divisible-And-Non-divisible-Sums-Difference/README.md, leetcode/2801-2900/2894.Divisible-And-Non-divisible-Sums-Difference/Solution.go, leetcode/2801-2900/2894.Divisible-And-Non-divisible-Sums-Difference/Solution_test.go
Add solution and test-cases for problem 2894
=> Add solution and test-cases for problem 2894

leetcode/1501-1600/1593.Split-a-String-Into-the-Max-Number-of-Unique-Substrings/README.md, leetcode/1501-1600/1593.Split-a-String-Into-the-Max-Number-of-Unique-Substrings/Solution.go, leetcode/1501-1600/1593.Split-a-String-Into-the-Max-Number-of-Unique-Substrings/Solution_test.go
Add solution and test-cases for problem 1593
=> Add solution and test-cases for problem 1593

leetcode/2801-2900/2848.Points-That-Intersect-With-Cars/README.md, leetcode/2801-2900/2848.Points-That-Intersect-With-Cars/Solution.go, leetcode/2801-2900/2848.Points-That-Intersect-With-Cars/Solution_test.go
Add solution and test-cases for problem 2848
=> Add solution and test-cases for problem 2848

leetcode/2901-3000/2938.Separate-Black-and-White-Balls/README.md, leetcode/2901-3000/2938.Separate-Black-and-White-Balls/Solution.go, leetcode/2901-3000/2938.Separate-Black-and-White-Balls/Solution_test.go
Add solution and test-cases for problem 2938
=> Add solution and test-cases for problem 2938

leetcode/901-1000/0962.Maximum-Width-Ramp/README.md, leetcode/901-1000/0962.Maximum-Width-Ramp/Solution.go, leetcode/901-1000/0962.Maximum-Width-Ramp/Solution_test.go
Add solution and test-cases for problem 962
=> Add solution and test-cases for problem 962

leetcode/1401-1500/1492.The-kth-Factor-of-n/README.md, leetcode/1401-1500/1492.The-kth-Factor-of-n/Solution.go, leetcode/1401-1500/1492.The-kth-Factor-of-n/Solution_test.go
Add solution and test-cases for problem 1492
=> Add solution and test-cases for problem 1492

leetcode/1901-2000/1963.Minimum-Number-of-Swaps-to-Make-the-String-Balanced/README.md, leetcode/1901-2000/1963.Minimum-Number-of-Swaps-to-Make-the-String-Balanced/Solution.go, leetcode/1901-2000/1963.Minimum-Number-of-Swaps-to-Make-the-String-Balanced/Solution_test.go
Add solution and test-cases for problem 1963
=> Add solution and test-cases for problem 1963

leetcode/1801-1900/1813.Sentence-Similarity-III/README.md, leetcode/1801-1900/1813.Sentence-Similarity-III/Solution.go, leetcode/1801-1900/1813.Sentence-Similarity-III/Solution_test.go
Add solution and test-cases for problem 1813
=> Add solution and test-cases for problem 1813

leetcode/1301-1400/1331.Rank-Transform-of-an-Array/README.md, leetcode/1301-1400/1331.Rank-Transform-of-an-Array/Solution.go, leetcode/1301-1400/1331.Rank-Transform-of-an-Array/Solution_test.go
Add solution and test-cases for problem 1331
=> Add solution and test-cases for problem 1331

leetcode/901-1000/0949.Largest-Time-for-Given-Digits/README.md, leetcode/901-1000/0949.Largest-Time-for-Given-Digits/Solution.go, leetcode/901-1000/0949.Largest-Time-for-Given-Digits/Solution_test.go
Add solution and test-cases for problem 949
=> Add solution and test-cases for problem 949

leetcode/2401-2500/2416.Sum-of-Prefix-Scores-of-Strings/README.md, leetcode/2401-2500/2416.Sum-of-Prefix-Scores-of-Strings/Solution.go, leetcode/2401-2500/2416.Sum-of-Prefix-Scores-of-Strings/Solution_test.go
Add solution and test-cases for problem 2416
=> Add solution and test-cases for problem 2416

leetcode/801-900/0862.Shortest-Subarray-with-Sum-at-Least-K/README.md, leetcode/801-900/0862.Shortest-Subarray-with-Sum-at-Least-K/Solution.go, leetcode/801-900/0862.Shortest-Subarray-with-Sum-at-Least-K/Solution_test.go
Add solution and test-cases for problem 862
=> Add solution and test-cases for problem 862

leetcode/3201-3300/3255.Find-the-Power-of-K-Size-Subarrays-II/README.md, leetcode/3201-3300/3255.Find-the-Power-of-K-Size-Subarrays-II/Solution.go, leetcode/3201-3300/3255.Find-the-Power-of-K-Size-Subarrays-II/Solution_test.go
Add solution and test-cases for problem 3255
=> Add solution and test-cases for problem 3255

leetcode/2901-3000/2914.Minimum-Number-of-Changes-to-Make-Binary-String-Beautiful/README.md, leetcode/2901-3000/2914.Minimum-Number-of-Changes-to-Make-Binary-String-Beautiful/Solution.go, leetcode/2901-3000/2914.Minimum-Number-of-Changes-to-Make-Binary-String-Beautiful/Solution_test.go
Add solution and test-cases for problem 2914
=> Add solution and test-cases for problem 2914

leetcode/2401-2500/2490.Circular-Sentence/README.md, leetcode/2401-2500/2490.Circular-Sentence/Solution.go, leetcode/2401-2500/2490.Circular-Sentence/Solution_test.go
Add solution and test-cases for problem 2490
=> Add solution and test-cases for problem 2490

leetcode/2801-2900/2872.Maximum-Number-Of-K-Divisible-Components/README.md, leetcode/2801-2900/2872.Maximum-Number-Of-K-Divisible-Components/Solution.go, leetcode/2801-2900/2872.Maximum-Number-Of-K-Divisible-Components/Solution_test.go
Add solution and test-cases for problem 2872
=> Add solution and test-cases for problem 2872

leetcode/1001-1100/1034.Coloring-A-Border/README.md, leetcode/1001-1100/1034.Coloring-A-Border/Solution.go, leetcode/1001-1100/1034.Coloring-A-Border/Solution_test.go
Add solution and test-cases for problem 1034
=> Add solution and test-cases for problem 1034

leetcode/1701-1800/1726.Tuple-with-Same-Product/README.md, leetcode/1701-1800/1726.Tuple-with-Same-Product/Solution.go, leetcode/1701-1800/1726.Tuple-with-Same-Product/Solution_test.go
Add solution and test-cases for problem 1726
=> Add solution and test-cases for problem 1726

leetcode/1701-1800/1792.Maximum-Average-Pass-Ratio/README.md, leetcode/1701-1800/1792.Maximum-Average-Pass-Ratio/Solution.go, leetcode/1701-1800/1792.Maximum-Average-Pass-Ratio/Solution_test.go
Add solution and test-cases for problem 1792
=> Add solution and test-cases for problem 1792

leetcode/2701-2800/2762.Continuous-Subarrays/README.md, leetcode/2701-2800/2762.Continuous-Subarrays/Solution.go, leetcode/2701-2800/2762.Continuous-Subarrays/Solution_test.go
Add solution and test-cases for problem 2762
=> Add solution and test-cases for problem 2762

leetcode/2501-2600/2593.Find-Score-of-an-Array-After-Marking-All-Elements/README.md, leetcode/2501-2600/2593.Find-Score-of-an-Array-After-Marking-All-Elements/Solution.go, leetcode/2501-2600/2593.Find-Score-of-an-Array-After-Marking-All-Elements/Solution_test.go
Add solution and test-cases for problem 2593
=> Add solution and test-cases for problem 2593

leetcode/2501-2600/2558.Take-Gifts-From-the-Richest-Pile/README.md, leetcode/2501-2600/2558.Take-Gifts-From-the-Richest-Pile/Solution.go, leetcode/2501-2600/2558.Take-Gifts-From-the-Richest-Pile/Solution_test.go
Add solution and test-cases for problem 2558
=> Add solution and test-cases for problem 2558

leetcode/2701-2800/2779.Maximum-Beauty-of-an-Array-After-Applying-Operation/README.md, leetcode/2701-2800/2779.Maximum-Beauty-of-an-Array-After-Applying-Operation/Solution.go, leetcode/2701-2800/2779.Maximum-Beauty-of-an-Array-After-Applying-Operation/Solution_test.go
Add solution and test-cases for problem 2779
=> Add solution and test-cases for problem 2779

leetcode/3101-3200/3152.Special-Array-II/README.md, leetcode/3101-3200/3152.Special-Array-II/Solution.go, leetcode/3101-3200/3152.Special-Array-II/Solution_test.go
Add solution and test-cases for problem 3152
=> Add solution and test-cases for problem 3152

leetcode/2501-2600/2554.Maximum-Number-of-Integers-to-Choose-From-a-Range-I/README.md, leetcode/2501-2600/2554.Maximum-Number-of-Integers-to-Choose-From-a-Range-I/Solution.go, leetcode/2501-2600/2554.Maximum-Number-of-Integers-to-Choose-From-a-Range-I/Solution_test.go
Add solution and test-cases for problem 2554
=> Add solution and test-cases for problem 2554

leetcode/2801-2900/2825.Make-String-a-Subsequence-Using-Cyclic-Increments/README.md, leetcode/2801-2900/2825.Make-String-a-Subsequence-Using-Cyclic-Increments/Solution.go, leetcode/2801-2900/2825.Make-String-a-Subsequence-Using-Cyclic-Increments/Solution_test.go
Add solution and test-cases for problem 2825
=> Add solution and test-cases for problem 2825

leetcode/1401-1500/1455.Check-If-a-Word-Occurs-As-a-Prefix-of-Any-Word-in-a-Sentence/README.md, leetcode/1401-1500/1455.Check-If-a-Word-Occurs-As-a-Prefix-of-Any-Word-in-a-Sentence/Solution.go, leetcode/1401-1500/1455.Check-If-a-Word-Occurs-As-a-Prefix-of-Any-Word-in-a-Sentence/Solution_test.go
Add solution and test-cases for problem 1455
=> Add solution and test-cases for problem 1455

leetcode/2701-2800/2729.Check-if-The-Number-is-Fascinating/README.md, leetcode/2701-2800/2729.Check-if-The-Number-is-Fascinating/Solution.go, leetcode/2701-2800/2729.Check-if-The-Number-is-Fascinating/Solution_test.go
Add solution and test-cases for problem 2729
=> Add solution and test-cases for problem 2729

leetcode/2501-2600/2516.Take-K-of-Each-Character-From-Left-and-Right/README.md, leetcode/2501-2600/2516.Take-K-of-Each-Character-From-Left-and-Right/Solution.go, leetcode/2501-2600/2516.Take-K-of-Each-Character-From-Left-and-Right/Solution_test.go
Add solution and test-cases for problem 2516
=> Add solution and test-cases for problem 2516

leetcode/1601-1700/1652.Defuse-the-Bomb/README.md, leetcode/1601-1700/1652.Defuse-the-Bomb/Solution.go, leetcode/1601-1700/1652.Defuse-the-Bomb/Solution_test.go
Add solution and test-cases for problem 1652
=> Add solution and test-cases for problem 1652

leetcode/1401-1500/1471.The-k-Strongest-Values-in-an-Array/README.md, leetcode/1401-1500/1471.The-k-Strongest-Values-in-an-Array/Solution.go, leetcode/1401-1500/1471.The-k-Strongest-Values-in-an-Array/Solution_test.go
Add solution and test-cases for problem 1471
=> Add solution and test-cases for problem 1471

leetcode/501-600/0561.Array-Partition/README.md, leetcode/501-600/0561.Array-Partition/Solution.go, leetcode/501-600/0561.Array-Partition/Solution_test.go
Add solution and test-cases for problem 561
=> Add solution and test-cases for problem 561

leetcode/601-700/0689.Maximum-Sum-of-3-Non-Overlapping-Subarrays/README.md, leetcode/601-700/0689.Maximum-Sum-of-3-Non-Overlapping-Subarrays/Solution.go, leetcode/601-700/0689.Maximum-Sum-of-3-Non-Overlapping-Subarrays/Solution_test.go
Add solution and test-cases for problem 689
=> Add solution and test-cases for problem 689

leetcode/2101-2200/2185.Counting-Words-With-a-Given-Prefix/README.md, leetcode/2101-2200/2185.Counting-Words-With-a-Given-Prefix/Solution.go, leetcode/2101-2200/2185.Counting-Words-With-a-Given-Prefix/Solution_test.go
Add solution and test-cases for problem 2185
=> Add solution and test-cases for problem 2185

leetcode/1401-1500/1408.String-Matching-in-an-Array/README.md, leetcode/1401-1500/1408.String-Matching-in-an-Array/Solution.go, leetcode/1401-1500/1408.String-Matching-in-an-Array/Solution_test.go
Add solution and test-cases for problem 1408
=> Add solution and test-cases for problem 1408

leetcode/1701-1800/1745.Palindrome-Partitioning-IV/README.md, leetcode/1701-1800/1745.Palindrome-Partitioning-IV/Solution.go, leetcode/1701-1800/1745.Palindrome-Partitioning-IV/Solution_test.go
Add solution and test-cases for problem 1745
=> Add solution and test-cases for problem 1745

leetcode/101-200/0132.Palindrome-Partitioning-II/README.md, leetcode/101-200/0132.Palindrome-Partitioning-II/Solution.go, leetcode/101-200/0132.Palindrome-Partitioning-II/Solution_test.go
Add solution and test-cases for problem 132
=> Add solution and test-cases for problem 132

leetcode/2201-2300/2270.Number-of-Ways-to-Split-Array/README.md, leetcode/2201-2300/2270.Number-of-Ways-to-Split-Array/Solution.go, leetcode/2201-2300/2270.Number-of-Ways-to-Split-Array/Solution_test.go
Add solution and test-cases for problem 2270
=> Add solution and test-cases for problem 2270

leetcode/2501-2600/2559.Count-Vowel-Strings-in-Ranges/README.md, leetcode/2501-2600/2559.Count-Vowel-Strings-in-Ranges/Solution.go, leetcode/2501-2600/2559.Count-Vowel-Strings-in-Ranges/Solution_test.go
Add solution and test-cases for problem 2559
=> Add solution and test-cases for problem 2559

leetcode/1401-1500/1415.The-k-th-Lexicographical-String-of-All-Happy-Strings-of-Length-n/README.md, leetcode/1401-1500/1415.The-k-th-Lexicographical-String-of-All-Happy-Strings-of-Length-n/Solution.go, leetcode/1401-1500/1415.The-k-th-Lexicographical-String-of-All-Happy-Strings-of-Length-n/Solution_test.go
Add solution and test-cases for problem 1415
=> Add solution and test-cases for problem 1415

leetcode/2301-2400/2375.Construct-Smallest-Number-From-DI-String/README.md, leetcode/2301-2400/2375.Construct-Smallest-Number-From-DI-String/Solution.go, leetcode/2301-2400/2375.Construct-Smallest-Number-From-DI-String/Solution_test.go
Add solution and test-cases for problem  2375
=> Add solution and test-cases for problem  2375

leetcode/901-1000/0942.DI-String-Match/README.md, leetcode/901-1000/0942.DI-String-Match/Solution.go, leetcode/901-1000/0942.DI-String-Match/Solution_test.go
Add solution and test-cases for problem 942
=> Add solution and test-cases for problem 942

leetcode/1301-1400/1390.Four-Divisors/README.md, leetcode/1301-1400/1390.Four-Divisors/Solution.go, leetcode/1301-1400/1390.Four-Divisors/Solution_test.go
Add solution and test-cases for problem 1390
=> Add solution and test-cases for problem 1390

leetcode/3101-3200/3174.Clear-Digits/README.md, leetcode/3101-3200/3174.Clear-Digits/Solution.go, leetcode/3101-3200/3174.Clear-Digits/Solution_test.go
Add solution and test-cases for problem 3174
=> Add solution and test-cases for problem 3174

leetcode/2301-2400/2364.Count-Number-of-Bad-Pairs/README.md, leetcode/2301-2400/2364.Count-Number-of-Bad-Pairs/Solution.go, leetcode/2301-2400/2364.Count-Number-of-Bad-Pairs/Solution_test.go
Add solution and test-cases for problem 2364
=> Add solution and test-cases for problem 2364

leetcode/2301-2400/2349.Design-a-Number-Container-System/README.md, leetcode/2301-2400/2349.Design-a-Number-Container-System/Solution.go, leetcode/2301-2400/2349.Design-a-Number-Container-System/Solution_test.go
Add solution and test-cases for problem 2349
=> Add solution and test-cases for problem 2349

leetcode/1201-1300/1283.Find-the-Smallest-Divisor-Given-a-Threshold/README.md, leetcode/1201-1300/1283.Find-the-Smallest-Divisor-Given-a-Threshold/Solution.go, leetcode/1201-1300/1283.Find-the-Smallest-Divisor-Given-a-Threshold/Solution_test.go
Add solution and test-cases for problem 1283
=> Add solution and test-cases for problem 1283

leetcode/1701-1800/1800.Maximum-Ascending-Subarray-Sum/README.md, leetcode/1701-1800/1800.Maximum-Ascending-Subarray-Sum/Solution.go, leetcode/1701-1800/1800.Maximum-Ascending-Subarray-Sum/Solution_test.go
Add solution and test-cases for problem 1800
=> Add solution and test-cases for problem 1800

leetcode/3101-3200/3105.Longest-Strictly-Increasing-or-Strictly-Decreasing-Subarray/README.md, leetcode/3101-3200/3105.Longest-Strictly-Increasing-or-Strictly-Decreasing-Subarray/Solution.go, leetcode/3101-3200/3105.Longest-Strictly-Increasing-or-Strictly-Decreasing-Subarray/Solution_test.go
Add solution and test-cases for problem 3105
=> Add solution and test-cases for problem 3105

leetcode/1101-1200/1115.Print-FooBar-Alternately/README.md, leetcode/1101-1200/1115.Print-FooBar-Alternately/Solution.go, leetcode/1101-1200/1115.Print-FooBar-Alternately/Solution_test.go
Add solution and test-cases for problem 1115
=> Add solution and test-cases for problem 1115

leetcode/3101-3200/3151.Special-Array-I/README.md, leetcode/3101-3200/3151.Special-Array-I/Solution.go, leetcode/3101-3200/3151.Special-Array-I/Solution_test.go
Add solution and test-cases for problem 3151
=> Add solution and test-cases for problem 3151

leetcode/801-900/0827.Making-A-Large-Island/README.md, leetcode/801-900/0827.Making-A-Large-Island/Solution.go, leetcode/801-900/0827.Making-A-Large-Island/Solution_test.go
Add solution and test-cases for problem 827
=> Add solution and test-cases for problem 827

leetcode/501-600/0600.Non-negative-Integers-without-Consecutive-Ones/README.md, leetcode/501-600/0600.Non-negative-Integers-without-Consecutive-Ones/Solution.go, leetcode/501-600/0600.Non-negative-Integers-without-Consecutive-Ones/Solution_test.go
Add solution and test-cases for problem 600
=> Add solution and test-cases for problem 600

leetcode/2101-2200/2115.Find-All-Possible-Recipes-from-Given-Supplies/README.md, leetcode/2101-2200/2115.Find-All-Possible-Recipes-from-Given-Supplies/Solution.go, leetcode/2101-2200/2115.Find-All-Possible-Recipes-from-Given-Supplies/Solution_test.go
Add solution and test-cases for problem 2115
=> Add solution and test-cases for problem 2115

leetcode/2901-3000/2948.Make-Lexicographically-Smallest-Array-by-Swapping-Elements/README.md, leetcode/2901-3000/2948.Make-Lexicographically-Smallest-Array-by-Swapping-Elements/Solution.go, leetcode/2901-3000/2948.Make-Lexicographically-Smallest-Array-by-Swapping-Elements/Solution_test.go
Add solution and test-cases for problem 2948
=> Add solution and test-cases for problem 2948

leetcode/1001-1100/1089.Duplicate-Zeros/README.md, leetcode/1001-1100/1089.Duplicate-Zeros/Solution.go, leetcode/1001-1100/1089.Duplicate-Zeros/Solution_test.go
Add solution and test-cases for problem 1089
=> Add solution and test-cases for problem 1089

leetcode/1601-1700/1664.Ways-to-Make-a-Fair-Array/README.md, leetcode/1601-1700/1664.Ways-to-Make-a-Fair-Array/Solution.go, leetcode/1601-1700/1664.Ways-to-Make-a-Fair-Array/Solution_test.go
Add solution and test-cases for problem  1664
=> Add solution and test-cases for problem  1664

leetcode/2601-2700/2683.Neighboring-Bitwise-XOR/README.md, leetcode/2601-2700/2683.Neighboring-Bitwise-XOR/Solution.go, leetcode/2601-2700/2683.Neighboring-Bitwise-XOR/Solution_test.go
Add solution and test-cases for problem 2683
=> Add solution and test-cases for problem 2683

leetcode/2601-2700/2657.Find-the-Prefix-Common-Array-of-Two-Arrays/README.md, leetcode/2601-2700/2657.Find-the-Prefix-Common-Array-of-Two-Arrays/Solution.go, leetcode/2601-2700/2657.Find-the-Prefix-Common-Array-of-Two-Arrays/Solution_test.go
Add solution and test-cases for problem 2657
=> Add solution and test-cases for problem 2657

leetcode/3201-3300/3223.Minimum-Length-of-String-After-Operations/README.md, leetcode/3201-3300/3223.Minimum-Length-of-String-After-Operations/Solution.go, leetcode/3201-3300/3223.Minimum-Length-of-String-After-Operations/Solution_test.go
Add solution and test-cases for problem 3223
=> Add solution and test-cases for problem 3223

leetcode/1701-1800/1780.Check-if-Number-is-a-Sum-of-Powers-of-Three/README.md, leetcode/1701-1800/1780.Check-if-Number-is-a-Sum-of-Powers-of-Three/Solution.go, leetcode/1701-1800/1780.Check-if-Number-is-a-Sum-of-Powers-of-Three/Solution_test.go
Add solution and test-cases for problem 1780
=> Add solution and test-cases for problem 1780
