6boris/awesome-golang-algorithm

- src/0235.Lowest-Common-Ancestor-of-a-Binary-Search-Tree/README.md
- src/0235.Lowest-Common-Ancestor-of-a-Binary-Search-Tree/Solution.go
- src/0235.Lowest-Common-Ancestor-of-a-Binary-Search-Tree/Solution_test.go
- src/0236.Lowest-Common-Ancestor-of-a-Binary-Tree/README.md
- src/0236.Lowest-Common-Ancestor-of-a-Binary-Tree/Solution.go
- src/0236.Lowest-Common-Ancestor-of-a-Binary-Tree/Solution_test.go
- src/0703.Kth-Largest-Element-in-a-Stream/README.md
> Add 235&235 

- src/0344.Reverse-String/README.md
- src/0344.Reverse-String/Solution.go
- src/0344.Reverse-String/Solution_test.go
- src/0392.Is-Subsequence/README.md
- src/0392.Is-Subsequence/Solution.go
- src/0392.Is-Subsequence/Solution_test.go
Reverse string solution. Inputs modified from leetcode a bit to better suit test cases.
> Reverse string solution

- src/0392.Is-Subsequence/README.md
- src/0392.Is-Subsequence/Solution.go
- src/0392.Is-Subsequence/Solution_test.go
Solution to the is-subsequence problem :)
> add is-subsequence solution

- leetcode/701-800/0718.Maximum-Length-of-Repeated-Subarray/README.md
- leetcode/701-800/0718.Maximum-Length-of-Repeated-Subarray/Solution.go
- leetcode/701-800/0718.Maximum-Length-of-Repeated-Subarray/Solution_test.go
:sparkles: Add solution and testcases to problem 718
> New solution

- leetcode/201-300/0205.Isomorphic-Strings/README.md
- leetcode/201-300/0205.Isomorphic-Strings/Solution.go
- leetcode/201-300/0205.Isomorphic-Strings/Solution_test.go
Add solution and test-cases for problem 205
> Add solution and test-cases for problem 205

- leetcode/401-500/0415.Add-Strings/README.md
- leetcode/401-500/0415.Add-Strings/Solution.go
- leetcode/401-500/0415.Add-Strings/Solution_test.go
Add solution and test-cases for problem 415
> Add solution and test-cases for problem 415

- leetcode/1301-1400/1314.Matrix-Block-Sum/README.md
- leetcode/1301-1400/1314.Matrix-Block-Sum/Solution.go
- leetcode/1301-1400/1314.Matrix-Block-Sum/Solution_test.go
Add solution and test-cases for problem 1314
> Add solution and test-cases for problem 1314

- leetcode/101-200/0155.Min-Stack/Solution.go
- leetcode/101-200/0155.Min-Stack/Solution_test.go
- leetcode/301-400/0341.Flatten-Nested-List-Iterator/README.md
- leetcode/301-400/0341.Flatten-Nested-List-Iterator/Solution.go
- leetcode/301-400/0341.Flatten-Nested-List-Iterator/Solution_test.go
- leetcode/701-800/0729.My-Calendar-I/README.md
- leetcode/701-800/0729.My-Calendar-I/Solution.go
- leetcode/701-800/0729.My-Calendar-I/Solution_test.go
Add solution and test-cases for problem 729
> Add solution and test-cases for problem 729

- leetcode/1001-1100/1094.Car-Pooling/README.md
- leetcode/1001-1100/1094.Car-Pooling/Solution.go
- leetcode/1001-1100/1094.Car-Pooling/Solution_test.go
Add solution and test-cases for problem 1094
> Add solution and test-cases for problem 1094

- leetcode/101-200/0131.Palindrome-Partitioning/README.md
- leetcode/101-200/0131.Palindrome-Partitioning/Solution.go
- leetcode/101-200/0131.Palindrome-Partitioning/Solution_test.go
Add solution and test-cases for problem 131
> Add solution and test-cases for problem 131

- leetcode/901-1000/0997.Find-the-Town-Judge/README.md
- leetcode/901-1000/0997.Find-the-Town-Judge/Solution.go
- leetcode/901-1000/0997.Find-the-Town-Judge/Solution_test.go
Add solution and test-cases for problem 997
> Add solution and test-cases for problem 997

- leetcode/301-400/0312.Burst-Balloons/README.md
- leetcode/301-400/0312.Burst-Balloons/Solution.go
- leetcode/301-400/0312.Burst-Balloons/Solution_test.go
Add solution and test-cases for problem 312
> Add solution and test-cases for problem 312

- leetcode/501-600/0543.Diameter-of-Binary-Tree/Solution_test.go
- leetcode/501-600/0557.Reverse-Words-in-a-String-III/README.md
- leetcode/501-600/0557.Reverse-Words-in-a-String-III/Solution.go
- leetcode/501-600/0557.Reverse-Words-in-a-String-III/Solution_test.go
Add solution and test-cases for problem 557
> Add solution and test-cases for problem 557

- leetcode/1-100/0006.ZigZag-Conversion/README.md
- leetcode/1-100/0006.ZigZag-Conversion/Solution.go
- leetcode/1-100/0006.ZigZag-Conversion/Solution_test.go
Add solution and test-cases and README for problem 6
> Add solution and test-cases and README for problem 6

- leetcode/101-200/0169.Majority-Element/README.md
- leetcode/101-200/0169.Majority-Element/Solution.go
- leetcode/101-200/0169.Majority-Element/Solution_test.go
Add solution and README for problem 169
> Add solution and README for problem 169

- leetcode/601-700/0673.Number-of-Longest-Increasing-Subsequence/README.md
- leetcode/601-700/0673.Number-of-Longest-Increasing-Subsequence/Solution.go
- leetcode/601-700/0673.Number-of-Longest-Increasing-Subsequence/Solution_test.go
Add solution and test-cases for problem  673
> Add solution and test-cases for problem  673

- leetcode/201-300/0228.Summary-Ranges/README.md
- leetcode/201-300/0228.Summary-Ranges/Solution.go
- leetcode/201-300/0228.Summary-Ranges/Solution_test.go
Add solution and test-cases for problem 228
> Add solution and test-cases for problem 228

- leetcode/701-800/0763.Partition-Labels/README.md
- leetcode/701-800/0763.Partition-Labels/Solution.go
- leetcode/701-800/0763.Partition-Labels/Solution_test.go
Add solution and test-cases for problem 763
> Add solution and test-cases for problem 763

- leetcode/101-200/0172.Factorial-Trailing-Zeroes/README.md
- leetcode/101-200/0172.Factorial-Trailing-Zeroes/Solution.go
- leetcode/101-200/0172.Factorial-Trailing-Zeroes/Solution_test.go
Add solution and test-cases for problem 172
> Add solution and test-cases for problem 172

- leetcode/301-400/0357.Count-Numbers-with-Unique-Digits/README.md
- leetcode/301-400/0357.Count-Numbers-with-Unique-Digits/Solution.go
- leetcode/301-400/0357.Count-Numbers-with-Unique-Digits/Solution_test.go
Add solution and test-cases for problem 357
> Add solution and test-cases for problem 357

- leetcode/201-300/0279.Perfect-Squares/README.md
- leetcode/201-300/0279.Perfect-Squares/Solution.go
- leetcode/201-300/0279.Perfect-Squares/Solution_test.go
Add solution and test-cases for problem 279
> Add solution and test-cases for problem 279

- leetcode/301-400/0396.Rotate-Function/README.md
- leetcode/301-400/0396.Rotate-Function/Solution.go
- leetcode/301-400/0396.Rotate-Function/Solution_test.go
Add solution and test-cases for problem 396
> Add solution and test-cases for problem 396

- leetcode/901-1000/0905.Sort-Array-By-Parity/README.md
- leetcode/901-1000/0905.Sort-Array-By-Parity/Solution.go
- leetcode/901-1000/0905.Sort-Array-By-Parity/Solution_test.go
Add solution and test-cases for problem 905
> Add solution and test-cases for problem 905

- leetcode/801-900/0844.Backspace-String-Compare/README.md
- leetcode/801-900/0844.Backspace-String-Compare/Solution.go
- leetcode/801-900/0844.Backspace-String-Compare/Solution_test.go
Add solution and test-cases for problem 844
> Add solution and test-cases for problem 844

- leetcode/1001-1100/1005.Maximize-Sum-Of-Array-After-K-Negations/README.md
- leetcode/1001-1100/1005.Maximize-Sum-Of-Array-After-K-Negations/Solution.go
- leetcode/1001-1100/1005.Maximize-Sum-Of-Array-After-K-Negations/Solution_test.go
Add solution and test-cases for problem 1005
> Add solution and test-cases for problem 1005

- leetcode/901-1000/0925.Long-Pressed-Name/README.md
- leetcode/901-1000/0925.Long-Pressed-Name/Solution.go
- leetcode/901-1000/0925.Long-Pressed-Name/Solution_test.go
Add solution and test-cases for problem  925
> Add solution and test-cases for problem  925

- leetcode/601-700/0647.Palindromic-Substrings/README.md
- leetcode/601-700/0647.Palindromic-Substrings/Solution.go
- leetcode/601-700/0647.Palindromic-Substrings/Solution_test.go
Add solution and test-cases for problem  647
>  Add solution and test-cases for problem  647

- leetcode/401-500/0474.Ones-and-Zeroes/README.md
- leetcode/401-500/0474.Ones-and-Zeroes/Solution.go
- leetcode/401-500/0474.Ones-and-Zeroes/Solution_test.go
Add solution and test-cases for problem 474
> Add solution and test-cases for problem 474

- leetcode/1301-1400/1342.Number-of-Steps-to-Reduce-a-Number-to-Zero/README.md
- leetcode/1301-1400/1342.Number-of-Steps-to-Reduce-a-Number-to-Zero/Solution.go
- leetcode/1301-1400/1342.Number-of-Steps-to-Reduce-a-Number-to-Zero/Solution_test.go
Add solution and test-cases for problem 1342
> Add solution and test-cases for problem 1342

- leetcode/301-400/0318.Maximum-Product-of-Word-Lengths/README.md
- leetcode/301-400/0318.Maximum-Product-of-Word-Lengths/Solution.go
- leetcode/301-400/0318.Maximum-Product-of-Word-Lengths/Solution_test.go
Add solution and test-cases for problem 318
> Add solution and test-cases for problem 318

- leetcode/1401-1500/1480.Running-Sum-of-1d-Array/README.md
- leetcode/1401-1500/1480.Running-Sum-of-1d-Array/Solution.go
- leetcode/1401-1500/1480.Running-Sum-of-1d-Array/Solution_test.go
Add solution and test-cases for problem 1480
> Add solution and test-cases for problem 1480

- leetcode/1401-1500/1461.Check-If-a-String-Contains-All-Binary-Codes-of-Size-K/README.md
- leetcode/1401-1500/1461.Check-If-a-String-Contains-All-Binary-Codes-of-Size-K/Solution.go
- leetcode/1401-1500/1461.Check-If-a-String-Contains-All-Binary-Codes-of-Size-K/Solution_test.go
Add solution and test-cases for problem 1461
> Add solution and test-cases for problem 1461

- leetcode/1001-1100/1048.Longest-String-Chain/README.md
- leetcode/1001-1100/1048.Longest-String-Chain/Solution.go
- leetcode/1001-1100/1048.Longest-String-Chain/Solution_test.go
Add solution and test-cases for problem 1048
> Add solution and test-cases for problem 1048

- leetcode/501-600/0583.Delete-Operation-for-Two-Strings/README.md
- leetcode/501-600/0583.Delete-Operation-for-Two-Strings/Solution.go
- leetcode/501-600/0583.Delete-Operation-for-Two-Strings/Solution_test.go
Add solution and test-cases for problem 583
> Add solution and test-cases for problem 583

- leetcode/201-300/0209.Minimum-Size-Subarray-Sum/README.md
- leetcode/201-300/0209.Minimum-Size-Subarray-Sum/Solution.go
- leetcode/201-300/0209.Minimum-Size-Subarray-Sum/Solution_test.go
Add solution and test-cases for problem 209
> Add solution and test-cases for problem 209

- leetcode/601-700/0657.Robot-Return-to-Origin/README.md
- leetcode/601-700/0657.Robot-Return-to-Origin/Solution.go
- leetcode/601-700/0657.Robot-Return-to-Origin/Solution_test.go
Add solution and test-cases for problem 657
> Add solution and test-cases for problem 657

- leetcode/1401-1500/1423.Maximum-Points-You-Can-Obtain-from-Cards/README.md
- leetcode/1401-1500/1423.Maximum-Points-You-Can-Obtain-from-Cards/Solution.go
- leetcode/1401-1500/1423.Maximum-Points-You-Can-Obtain-from-Cards/Solution_test.go
Add solution and test-cases for problem 1423
> Add solution and test-cases for problem 1423

- leetcode/1601-1700/1689.Partitioning-Into-Minimum-Number-Of-Deci-Binary-Numbers/README.md
- leetcode/1601-1700/1689.Partitioning-Into-Minimum-Number-Of-Deci-Binary-Numbers/Solution.go
- leetcode/1601-1700/1689.Partitioning-Into-Minimum-Number-Of-Deci-Binary-Numbers/Solution_test.go
Add solution and test-cases for problem 1689
>  Add solution and test-cases for problem 1689

- leetcode/301-400/0376.Wiggle-Subsequence/Solution.go
- leetcode/301-400/0376.Wiggle-Subsequence/Solution_test.go
> Add solution for problem 376

- leetcode/1901-2000/1979.Find-Greatest-Common-Divisor-of-Array/README.md
- leetcode/1901-2000/1979.Find-Greatest-Common-Divisor-of-Array/Solution.go
- leetcode/1901-2000/1979.Find-Greatest-Common-Divisor-of-Array/Solution_test.go
Add solution and test-cases for problem 1979
> Add solution and test-cases for problem 1979

- leetcode/401-500/0462.Minimum-Moves-to-Equal-Array-Elements-II/README.md
- leetcode/401-500/0462.Minimum-Moves-to-Equal-Array-Elements-II/Solution.go
- leetcode/401-500/0462.Minimum-Moves-to-Equal-Array-Elements-II/Solution_test.go
Add solution and test-cases for problem 462
> Add solution and test-cases for problem 462

- leetcode/1601-1700/1696.Jump-Game-VI/README.md
- leetcode/1601-1700/1696.Jump-Game-VI/Solution.go
- leetcode/1601-1700/1696.Jump-Game-VI/Solution_test.go
Add solution and test-cases for problem 1696
> Add solution and test-cases for problem 1696

- leetcode/1101-1200/1175.Prime-Arrangements/README.md
- leetcode/1101-1200/1175.Prime-Arrangements/Solution.go
- leetcode/1101-1200/1175.Prime-Arrangements/Solution_test.go
Add solution and test-cases for problem 1175
> Add solution and test-cases for problem 1175

- leetcode/401-500/0495.Teemo-Attacking/README.md
- leetcode/401-500/0495.Teemo-Attacking/Solution.go
- leetcode/401-500/0495.Teemo-Attacking/Solution_test.go
Add solution and test-cases for problem 495
> Add solution and test-cases for problem 495

- leetcode/1401-1500/1460.Make-Two-Arrays-Equal-byReversing-Sub-arrays/README.md
- leetcode/1401-1500/1460.Make-Two-Arrays-Equal-byReversing-Sub-arrays/Solution.go
- leetcode/1401-1500/1460.Make-Two-Arrays-Equal-byReversing-Sub-arrays/Solution_test.go
Add solution and test-cases for problem 1460
> Add solution and test-cases for problem 1460

- leetcode/1401-1500/1464.Maximum-Product-of-Two-Elements-in-an-Array/README.md
- leetcode/1401-1500/1464.Maximum-Product-of-Two-Elements-in-an-Array/Solution.go
- leetcode/1401-1500/1464.Maximum-Product-of-Two-Elements-in-an-Array/Solution_test.go
Add solution and test-cases for problem 1464
> Add solution and test-cases for problem 1464

- leetcode/301-400/0378.Kth-Smallest-Element-in-a-Sorted-Matrix/README.md
- leetcode/301-400/0378.Kth-Smallest-Element-in-a-Sorted-Matrix/Solution.go
- leetcode/301-400/0378.Kth-Smallest-Element-in-a-Sorted-Matrix/Solution_test.go
Add solution and test-cases for problem  378
> Add solution and test-cases for problem  378

- leetcode/301-400/0307.Range-Sum-Query--Mutable/README.md
- leetcode/301-400/0307.Range-Sum-Query--Mutable/Solution.go
- leetcode/301-400/0307.Range-Sum-Query--Mutable/Solution_test.go
Add solution and test-cases for problem 307
> Add solution and test-cases for problem 307

- leetcode/1301-1400/1394.Find-Lucky-Number-in-an-Array/README.md
- leetcode/1301-1400/1394.Find-Lucky-Number-in-an-Array/Solution.go
- leetcode/1301-1400/1394.Find-Lucky-Number-in-an-Array/Solution_test.go
Add solution and README for problem 1394
> Add solution and README for problem 1394

- leetcode/401-500/0458.Poor-Pigs/README.md
- leetcode/401-500/0458.Poor-Pigs/Solution.go
- leetcode/401-500/0458.Poor-Pigs/Solution_test.go
Add solution and test-cases for problem  458
> Add solution and test-cases for problem  458

- leetcode/2201-2300/2239.Find-Closest-Number-to-Zero/README.md
- leetcode/2201-2300/2239.Find-Closest-Number-to-Zero/Solution.go
- leetcode/2201-2300/2239.Find-Closest-Number-to-Zero/Solution_test.go
Add solution and test-cases for problem 2239
> Add solution and test-cases for problem 2239

- leetcode/801-900/0804.Unique-Morse-Code-Words/README.md
- leetcode/801-900/0804.Unique-Morse-Code-Words/Solution.go
- leetcode/801-900/0804.Unique-Morse-Code-Words/Solution_test.go
Add solution and test-cases for problem 804
> Add solution and test-cases for problem 804

- leetcode/1701-1800/1736.Latest-Time-by-Replacing-Hidden-Digits/README.md
- leetcode/1701-1800/1736.Latest-Time-by-Replacing-Hidden-Digits/Solution.go
- leetcode/1701-1800/1736.Latest-Time-by-Replacing-Hidden-Digits/Solution_test.go
- leetcode/1701-1800/1758.Minimum-Changes-To-Make-Alternating-Binary-String/Solution_test.go
Add solution and test-cases for problem 1736
>  Add solution and test-cases for problem 1736

- leetcode/1701-1800/1758.Minimum-Changes-To-Make-Alternating-Binary-String/README.md
- leetcode/1701-1800/1758.Minimum-Changes-To-Make-Alternating-Binary-String/Solution.go
- leetcode/1701-1800/1758.Minimum-Changes-To-Make-Alternating-Binary-String/Solution_test.go
Add solution and test-cases for problem  1758
> Add solution and test-cases for problem  1758

- leetcode/301-400/0326.Power-of-Three/README.md
- leetcode/301-400/0326.Power-of-Three/Solution.go
- leetcode/301-400/0326.Power-of-Three/Solution_test.go
Add solution and test-cases for problem 326
> Add solution and test-cases for problem 326

- leetcode/301-400/0342.Power-of-Four/README.md
- leetcode/301-400/0342.Power-of-Four/Solution.go
- leetcode/301-400/0342.Power-of-Four/Solution_test.go
Add solution and test-cases for problem 342
> Add solution and test-cases for problem 342

- leetcode/1801-1900/1854.Maximum-Population-Year/README.md
- leetcode/1801-1900/1854.Maximum-Population-Year/Solution.go
- leetcode/1801-1900/1854.Maximum-Population-Year/Solution_test.go
Add solution and test-cases for problem 1854
> Add solution and test-cases for problem 1854

- leetcode/1001-1100/1046.Last-Stone-Weight/README.md
- leetcode/1001-1100/1046.Last-Stone-Weight/Solution.go
- leetcode/1001-1100/1046.Last-Stone-Weight/Solution_test.go
Add solution and test-cases for problem 1046
> Add solution and test-cases for problem 1046

- leetcode/901-1000/0967.Numbers-With-Same-Consecutive-Differences/README.md
- leetcode/901-1000/0967.Numbers-With-Same-Consecutive-Differences/Solution.go
- leetcode/901-1000/0967.Numbers-With-Same-Consecutive-Differences/Solution_test.go
Add solution and test-cases for problem 967
> Add solution and test-cases for problem 967

- leetcode/2201-2300/2278.Percentage-of-Letter-in-String/README.md
- leetcode/2201-2300/2278.Percentage-of-Letter-in-String/Solution.go
- leetcode/2201-2300/2278.Percentage-of-Letter-in-String/Solution_test.go
Add solution and test-cases for problem 2278
> Add solution and test-cases for problem 2278

- leetcode/1801-1900/1837.Sum-of-Digits-in-Base-K/README.md
- leetcode/1801-1900/1837.Sum-of-Digits-in-Base-K/Solution.go
- leetcode/1801-1900/1837.Sum-of-Digits-in-Base-K/Solution_test.go
Add solution and test-cases for problem 1837
> Add solution and test-cases for problem 1837

- leetcode/1501-1600/1502.Can-Make-Arithmetic-Progression-From-Sequence/README.md
- leetcode/1501-1600/1502.Can-Make-Arithmetic-Progression-From-Sequence/Solution.go
- leetcode/1501-1600/1502.Can-Make-Arithmetic-Progression-From-Sequence/Solution_test.go
Add solution and test-cases for problem 1502
> Add solution and test-cases for problem 1502

- leetcode/2001-2100/2011.Final-Value-of-Variable-After-Performing-Operations/README.md
- leetcode/2001-2100/2011.Final-Value-of-Variable-After-Performing-Operations/Solution.go
- leetcode/2001-2100/2011.Final-Value-of-Variable-After-Performing-Operations/Solution_test.go
Add solution and test-cases for problem 2011
> Add solution and test-cases for problem 2011

- leetcode/101-200/0188.Best-Time-to-Buy-and-Sell-Stock-IV/Solution.go
- leetcode/101-200/0188.Best-Time-to-Buy-and-Sell-Stock-IV/Solution_test.go
Add solution and test-cases for problem  188
> Add solution and test-cases for problem  188

- leetcode/2201-2300/2206.Divide-Array-Into-Equal-Pairs/README.md
- leetcode/2201-2300/2206.Divide-Array-Into-Equal-Pairs/Solution.go
- leetcode/2201-2300/2206.Divide-Array-Into-Equal-Pairs/Solution_test.go
Add solution and test-cases for problem 2206
> Add solution and test-cases for problem 2206

- leetcode/2301-2400/2395.Find-Subarrays-With-Equal-Sum/README.md
- leetcode/2301-2400/2395.Find-Subarrays-With-Equal-Sum/Solution.go
- leetcode/2301-2400/2395.Find-Subarrays-With-Equal-Sum/Solution_test.go
Add solution and test-cases for problem 2395
> Add solution and test-cases for problem 2395

- leetcode/2001-2100/2094.Finding-3-Digit-Even-Numbers/README.md
- leetcode/2001-2100/2094.Finding-3-Digit-Even-Numbers/Solution.go
- leetcode/2001-2100/2094.Finding-3-Digit-Even-Numbers/Solution_test.go
Add solution and test-cases for problem 2094
> Add solution and test-cases for problem 2094

- leetcode/601-700/0692.Top-K-Frequent-Words/README.md
- leetcode/601-700/0692.Top-K-Frequent-Words/Solution.go
- leetcode/601-700/0692.Top-K-Frequent-Words/Solution_test.go
Add solution and test-cases for problem 692
> Add solution and test-cases for problem 692

- leetcode/401-500/0496.Next-Greater-Element-I/README.md
- leetcode/401-500/0496.Next-Greater-Element-I/Solution.go
- leetcode/401-500/0496.Next-Greater-Element-I/Solution_test.go
Add solution and test-cases for problem 496
> Add solution and test-cases for problem 496

- leetcode/1601-1700/1662.Check-If-Two-String-Arrays-are-Equivalent/README.md
- leetcode/1601-1700/1662.Check-If-Two-String-Arrays-are-Equivalent/Solution.go
- leetcode/1601-1700/1662.Check-If-Two-String-Arrays-are-Equivalent/Solution_test.go
Add solution and test-cases for problem 1662
> Add solution and test-cases for problem 1662

- leetcode/2201-2300/2231.Largest-Number-After-Digit-Swaps-by-Parity/README.md
- leetcode/2201-2300/2231.Largest-Number-After-Digit-Swaps-by-Parity/Solution.go
- leetcode/2201-2300/2231.Largest-Number-After-Digit-Swaps-by-Parity/Solution_test.go
Add solution and test-cases for problem 2231
> Add solution and test-cases for problem 2231

- leetcode/601-700/0645.Set-Mismatch/README.md
- leetcode/601-700/0645.Set-Mismatch/Solution.go
- leetcode/601-700/0645.Set-Mismatch/Solution_test.go
Add solution and test-cases for problem 645
> Add solution and test-cases for problem 645

- leetcode/1601-1700/1608.Special-Array-With-X-Elements-Greater-Than-or-Equal-X/README.md
- leetcode/1601-1700/1608.Special-Array-With-X-Elements-Greater-Than-or-Equal-X/Solution.go
- leetcode/1601-1700/1608.Special-Array-With-X-Elements-Greater-Than-or-Equal-X/Solution_test.go
Add solution and test-cases for problem 1608
> Add solution and test-cases for problem 1608

- leetcode/1501-1600/1544.Make-The-String-Great/README.md
- leetcode/1501-1600/1544.Make-The-String-Great/Solution.go
- leetcode/1501-1600/1544.Make-The-String-Great/Solution_test.go
Add solution and test-cases for problem  1544
> Add solution and test-cases for problem  1544

- leetcode/1701-1800/1734.Decode-XORed-Permutation/README.md
- leetcode/1701-1800/1734.Decode-XORed-Permutation/Solution.go
- leetcode/1701-1800/1734.Decode-XORed-Permutation/Solution_test.go
Add solution and test-cases for problem 1734
> Add solution and test-cases for problem 1734

- leetcode/301-400/0345.Reverse-Vowels-of-a-String/README.md
- leetcode/301-400/0345.Reverse-Vowels-of-a-String/Solution.go
- leetcode/301-400/0345.Reverse-Vowels-of-a-String/Solution_test.go
Add solution and test-cases for problem 345
> Add solution and test-cases for problem 345

- leetcode/2201-2300/2210.Count-Hills-and-Valleys-in-an-Array/README.md
- leetcode/2201-2300/2210.Count-Hills-and-Valleys-in-an-Array/Solution.go
- leetcode/2201-2300/2210.Count-Hills-and-Valleys-in-an-Array/Solution_test.go
Add solution and test-cases for problem 2210
> Add solution and test-cases for problem 2210

- leetcode/2201-2300/2256.Minimum-Average-Difference/README.md
- leetcode/2201-2300/2256.Minimum-Average-Difference/Solution.go
- leetcode/2201-2300/2256.Minimum-Average-Difference/Solution_test.go
Add solution and test-cases for problem 2256
> Add solution and test-cases for problem 2256

- leetcode/401-500/0451.Sort-Characters-By-Frequency/README.md
- leetcode/401-500/0451.Sort-Characters-By-Frequency/Solution.go
- leetcode/401-500/0451.Sort-Characters-By-Frequency/Solution_test.go
Add solution and test-cases for problem 451
> Add solution and test-cases for problem 451

- leetcode/1601-1700/1657.Determine-if-Two-Strings-Are-Close/README.md
- leetcode/1601-1700/1657.Determine-if-Two-Strings-Are-Close/Solution.go
- leetcode/1601-1700/1657.Determine-if-Two-Strings-Are-Close/Solution_test.go
Add solution and test-cases for problem  1657
> Add solution and test-cases for problem  1657

- leetcode/1701-1800/1704.Determine-if-String-Halves-Are-Alike/README.md
- leetcode/1701-1800/1704.Determine-if-String-Halves-Are-Alike/Solution.go
- leetcode/1701-1800/1704.Determine-if-String-Halves-Are-Alike/Solution_test.go
Add solution and test-cases for problem 1704
> Add solution and test-cases for problem 1704

- leetcode/1201-1300/1207.Unique-Number-of-Occurrences/README.md
- leetcode/1201-1300/1207.Unique-Number-of-Occurrences/Solution.go
- leetcode/1201-1300/1207.Unique-Number-of-Occurrences/Solution_test.go
Add solution and test-cases for problem 1207
> Add solution and test-cases for problem 1207

- leetcode/301-400/0380.Insert-Delete-GetRandom-O-1/README.md
- leetcode/301-400/0380.Insert-Delete-GetRandom-O-1/Solution.go
- leetcode/301-400/0380.Insert-Delete-GetRandom-O-1/Solution_test.go
Add solution and test-cases for problem 380
> Add solution and test-cases for problem 380

- leetcode/2201-2300/2225.Find-Players-With-Zero-or-One-Losses/README.md
- leetcode/2201-2300/2225.Find-Players-With-Zero-or-One-Losses/Solution.go
- leetcode/2201-2300/2225.Find-Players-With-Zero-or-One-Losses/Solution_test.go
Add solution and test-cases for problem 2225
> Add solution and test-cases for problem 2225

- leetcode/601-700/0696.Count-Binary-Substrings/README.md
- leetcode/601-700/0696.Count-Binary-Substrings/Solution.go
- leetcode/601-700/0696.Count-Binary-Substrings/Solution_test.go
Add solution and test-cases for problem 696
> Add solution and test-cases for problem 696

- leetcode/401-500/0446.Arithmetic-Slices-II--Subsequence/README.md
- leetcode/401-500/0446.Arithmetic-Slices-II--Subsequence/Solution.go
- leetcode/401-500/0446.Arithmetic-Slices-II--Subsequence/Solution_test.go
Add solution and test-cases for problem 446
> Add solution and test-cases for problem 446

- leetcode/201-300/0299.Bulls-and-Cows/README.md
- leetcode/201-300/0299.Bulls-and-Cows/Solution.go
- leetcode/201-300/0299.Bulls-and-Cows/Solution_test.go
Add solution and test-cases for problem 299
> Add solution and test-cases for problem 299

- leetcode/2101-2200/2109.Adding-Spaces-to-a-String/README.md
- leetcode/2101-2200/2109.Adding-Spaces-to-a-String/Solution.go
- leetcode/2101-2200/2109.Adding-Spaces-to-a-String/Solution_test.go
Add solution and test-cases for problem 2109
> Add solution and test-cases for problem 2109

- leetcode/201-300/0258.Add-Digits/README.md
- leetcode/201-300/0258.Add-Digits/Solution.go
- leetcode/201-300/0258.Add-Digits/Solution_test.go
dd solution and test-cases for problem 258
> dd solution and test-cases for problem 258

- leetcode/901-1000/0947.Most-Stones-Removed-with-Same-Row-or-Column/README.md
- leetcode/901-1000/0947.Most-Stones-Removed-with-Same-Row-or-Column/Solution.go
- leetcode/901-1000/0947.Most-Stones-Removed-with-Same-Row-or-Column/Solution_test.go
Add solution and test-cases for problem 947
> Add solution and test-cases for problem 947

- leetcode/1001-1100/1003.Check-If-Word-Is-Valid-After-Substitutions/README.md
- leetcode/1001-1100/1003.Check-If-Word-Is-Valid-After-Substitutions/Solution.go
- leetcode/1001-1100/1003.Check-If-Word-Is-Valid-After-Substitutions/Solution_test.go
Add solution and test-cases for problem 1003
> Add solution and test-cases for problem 1003

- leetcode/1901-2000/1957.Delete-Characters-to-Make-Fancy-String/README.md
- leetcode/1901-2000/1957.Delete-Characters-to-Make-Fancy-String/Solution.go
- leetcode/1901-2000/1957.Delete-Characters-to-Make-Fancy-String/Solution_test.go
Add solution and test-cases for problem 1957
> Add solution and test-cases for problem 1957

- leetcode/901-1000/0901.Online-Stock-Span/README.md
- leetcode/901-1000/0901.Online-Stock-Span/Solution.go
- leetcode/901-1000/0901.Online-Stock-Span/Solution_test.go
Add solution and test-cases for problem 901
> Add solution and test-cases for problem 901

- leetcode/1401-1500/1441.Build-an-Array-With-Stack-Operations/README.md
- leetcode/1401-1500/1441.Build-an-Array-With-Stack-Operations/Solution.go
- leetcode/1401-1500/1441.Build-an-Array-With-Stack-Operations/Solution_test.go
Add solution and test-cases for problem 1441
> Add solution and test-cases for problem 1441

- leetcode/1-100/0093.Restore-IP-Addresses/README.md
- leetcode/1-100/0093.Restore-IP-Addresses/Solution.go
- leetcode/1-100/0093.Restore-IP-Addresses/Solution_test.go
Add solution and test-cases for problem 93
> Add solution and test-cases for problem 93

- leetcode/1301-1400/1310.XOR-Queries-of-a-Subarray/README.md
- leetcode/1301-1400/1310.XOR-Queries-of-a-Subarray/Solution.go
- leetcode/1301-1400/1310.XOR-Queries-of-a-Subarray/Solution_test.go
Add solution and test-cases for problem 1310
> Add solution and test-cases for problem 1310

- leetcode/901-1000/0907.Sum-of-Subarray-Minimums/README.md
- leetcode/901-1000/0907.Sum-of-Subarray-Minimums/Solution.go
- leetcode/901-1000/0907.Sum-of-Subarray-Minimums/Solution_test.go
Add solution and test-cases for problem 907
> Add solution and test-cases for problem 907

- leetcode/201-300/0201.Bitwise-AND-of-Numbers-Range/README.md
- leetcode/201-300/0201.Bitwise-AND-of-Numbers-Range/Solution.go
- leetcode/201-300/0201.Bitwise-AND-of-Numbers-Range/Solution_test.go
Add solution and test-cases for problem 201
> Add solution and test-cases for problem 201

- leetcode/1001-1100/1061.Lexicographically-Smallest-Equivalent-String/README.md
- leetcode/1001-1100/1061.Lexicographically-Smallest-Equivalent-String/Solution.go
- leetcode/1001-1100/1061.Lexicographically-Smallest-Equivalent-String/Solution_test.go
Add solution and test-cases for problem 1061
> Add solution and test-cases for problem 1061

- leetcode/901-1000/0926.Flip-String-to-Monotone-Increasing/README.md
- leetcode/901-1000/0926.Flip-String-to-Monotone-Increasing/Solution.go
- leetcode/901-1000/0926.Flip-String-to-Monotone-Increasing/Solution_test.go
Add solution and test-cases for problem 926
> Add solution and test-cases for problem 926

- leetcode/901-1000/0918.Maximum-Sum-Circular-Subarray/README.md
- leetcode/901-1000/0918.Maximum-Sum-Circular-Subarray/Solution.go
- leetcode/901-1000/0918.Maximum-Sum-Circular-Subarray/Solution_test.go
Add solution and test-cases for problem 918
> Add solution and test-cases for problem 918

- leetcode/401-500/0491.Increasing-Subsequences/README.md
- leetcode/401-500/0491.Increasing-Subsequences/Solution.go
- leetcode/401-500/0491.Increasing-Subsequences/Solution_test.go
Add solution and test-cases for problem  491
> Add solution and test-cases for problem  491

- leetcode/1801-1900/1856.Maximum-Subarray-Min-Product/README.md
- leetcode/1801-1900/1856.Maximum-Subarray-Min-Product/Solution.go
- leetcode/1801-1900/1856.Maximum-Subarray-Min-Product/Solution_test.go
Add solution and test-cases for problem 1856
> Add solution and test-cases for problem 1856

- leetcode/2101-2200/2104.Sum-of-Subarray-Ranges/README.md
- leetcode/2101-2200/2104.Sum-of-Subarray-Ranges/Solution.go
- leetcode/2101-2200/2104.Sum-of-Subarray-Ranges/Solution_test.go
Add solution and test-cases for problem 2104
> Add solution and test-cases for problem 2104

- leetcode/1201-1300/1248.Count-Number-of-Nice-Subarrays/README.md
- leetcode/1201-1300/1248.Count-Number-of-Nice-Subarrays/Solution.go
- leetcode/1201-1300/1248.Count-Number-of-Nice-Subarrays/Solution_test.go
Add solution and test-cases for problem 1248
> Add solution and test-cases for problem 1248

- leetcode/101-200/0134.Gas-Station/README.md
- leetcode/101-200/0134.Gas-Station/Solution.go
- leetcode/101-200/0134.Gas-Station/Solution_test.go
Add solution and test-cases for problem 134
> Add solution and test-cases for problem 134

- leetcode/1801-1900/1833.Maximum-Ice-Cream-Bars/README.md
- leetcode/1801-1900/1833.Maximum-Ice-Cream-Bars/Solution.go
- leetcode/1801-1900/1833.Maximum-Ice-Cream-Bars/Solution_test.go
Add solution and test-cases for problem  1833
> Add solution and test-cases for problem  1833

- leetcode/901-1000/0944.Delete-Columns-to-Make-Sorted/README.md
- leetcode/901-1000/0944.Delete-Columns-to-Make-Sorted/Solution.go
- leetcode/901-1000/0944.Delete-Columns-to-Make-Sorted/Solution_test.go
Add solution and test-cases for problem 944
> Add solution and test-cases for problem 944

- leetcode/1-100/0091.Decode-Ways/README.md
- leetcode/1-100/0091.Decode-Ways/Solution.go
- leetcode/1-100/0091.Decode-Ways/Solution_test.go
> Add solution for problem 91

- leetcode/501-600/0520.Detect-Capital/README.md
- leetcode/501-600/0520.Detect-Capital/Solution.go
- leetcode/501-600/0520.Detect-Capital/Solution_test.go
Add solution and test-cases for problem 520
> Add solution and test-cases for problem 520

- leetcode/201-300/0290.Word-Pattern/README.md
- leetcode/201-300/0290.Word-Pattern/Solution.go
- leetcode/201-300/0290.Word-Pattern/Solution_test.go
Add solution and test-cases for problem 290
> Add solution and test-cases for problem 290

- leetcode/1801-1900/1834.Single-Threaded-CPU/README.md
- leetcode/1801-1900/1834.Single-Threaded-CPU/Solution.go
- leetcode/1801-1900/1834.Single-Threaded-CPU/Solution_test.go
Add solution and test-cases for problem 1834
> Add solution and test-cases for problem 1834

- leetcode/1901-2000/1962.Remove-Stones-to-Minimize-the-Total/README.md
- leetcode/1901-2000/1962.Remove-Stones-to-Minimize-the-Total/Solution.go
- leetcode/1901-2000/1962.Remove-Stones-to-Minimize-the-Total/Solution_test.go
Add solution and test-cases for problem 1962
> Add solution and test-cases for problem 1962

- leetcode/2201-2300/2279.Maximum-Bags-With-Full-Capacity-of-Rocks/README.md
- leetcode/2201-2300/2279.Maximum-Bags-With-Full-Capacity-of-Rocks/Solution.go
- leetcode/2201-2300/2279.Maximum-Bags-With-Full-Capacity-of-Rocks/Solution_test.go
Add solution and test-cases for problem 2279
> Add solution and test-cases for problem 2279

- leetcode/1301-1400/1374.Generate-a-String-With-Characters-That-Have-Odd-Counts/README.md
- leetcode/1301-1400/1374.Generate-a-String-With-Characters-That-Have-Odd-Counts/Solution.go
- leetcode/1301-1400/1374.Generate-a-String-With-Characters-That-Have-Odd-Counts/Solution_test.go
Add solution and test-cases for problem 1374
> Add solution and test-cases for problem 1374

- leetcode/2301-2400/2389.Longest-Subsequence-With-Limited-Sum/README.md
- leetcode/2301-2400/2389.Longest-Subsequence-With-Limited-Sum/Solution.go
- leetcode/2301-2400/2389.Longest-Subsequence-With-Limited-Sum/Solution_test.go
Add solution and test-cases for problem 2389
> Add solution and test-cases for problem 2389

- leetcode/801-900/0886.Possible-Bipartition/README.md
- leetcode/801-900/0886.Possible-Bipartition/Solution.go
- leetcode/801-900/0886.Possible-Bipartition/Solution_test.go
Add solution and test-cases for problem  886
> Add solution and test-cases for problem  886

- leetcode/801-900/0841.Keys-and-Rooms/README.md
- leetcode/801-900/0841.Keys-and-Rooms/Solution.go
- leetcode/801-900/0841.Keys-and-Rooms/Solution_test.go
Add solution and test-cases for problem 841
> Add solution and test-cases for problem 841

- leetcode/701-800/0739.Daily-Temperatures/README.md
- leetcode/701-800/0739.Daily-Temperatures/Solution.go
- leetcode/701-800/0739.Daily-Temperatures/Solution_test.go
Add solution and test-cases for problem 739
> Add solution and test-cases for problem 739

- leetcode/101-200/0150.Evaluate-Reverse-Polish-Notation/README.md
- leetcode/101-200/0150.Evaluate-Reverse-Polish-Notation/Solution.go
- leetcode/101-200/0150.Evaluate-Reverse-Polish-Notation/Solution_test.go
Add solution and test-cases for problem 150
> Add solution and test-cases for problem 150

- leetcode/1101-1200/1143.Longest-Common-Subsequence/README.md
- leetcode/1101-1200/1143.Longest-Common-Subsequence/Solution.go
- leetcode/1101-1200/1143.Longest-Common-Subsequence/Solution_test.go
Add solution and test-cases for problem 1143
> Add solution and test-cases for problem 1143

- leetcode/1701-1800/1768.Merge-Strings-Alternately/README.md
- leetcode/1701-1800/1768.Merge-Strings-Alternately/Solution.go
- leetcode/1701-1800/1768.Merge-Strings-Alternately/Solution_test.go
Add solution and test-cases for problem 1768
> Add solution and test-cases for problem 1768

- leetcode/2101-2200/2148.Count-Elements-With-Strictly-Smaller-and-Greater-Elements-/README.md
- leetcode/2101-2200/2148.Count-Elements-With-Strictly-Smaller-and-Greater-Elements-/Solution.go
- leetcode/2101-2200/2148.Count-Elements-With-Strictly-Smaller-and-Greater-Elements-/Solution_test.go
Add solution and test-cases for problem 2148
> Add solution and test-cases for problem 2148

- leetcode/2301-2400/2367.Number-of-Arithmetic-Triplets/README.md
- leetcode/2301-2400/2367.Number-of-Arithmetic-Triplets/Solution.go
- leetcode/2301-2400/2367.Number-of-Arithmetic-Triplets/Solution_test.go
Add solution and test-cases for problem 2367
> Add solution and test-cases for problem 2367

- leetcode/1401-1500/1470.Shuffle-the-Array/README.md
- leetcode/1401-1500/1470.Shuffle-the-Array/Solution.go
- leetcode/1401-1500/1470.Shuffle-the-Array/Solution_test.go
Add solution and test-cases for problem  1470
> Add solution and test-cases for problem  1470

- leetcode/401-500/0438.Find-All-Anagrams-in-a-String/README.md
- leetcode/401-500/0438.Find-All-Anagrams-in-a-String/Solution.go
- leetcode/401-500/0438.Find-All-Anagrams-in-a-String/Solution_test.go
Add solution and test-cases for problem 438
> Add solution and test-cases for problem 438

- leetcode/501-600/0567.Permutation-in-String/README.md
- leetcode/501-600/0567.Permutation-in-String/Solution.go
- leetcode/501-600/0567.Permutation-in-String/Solution_test.go
Add solution and test-cases for problem 567
> Add solution and test-cases for problem 567

- leetcode/901-1000/0953.Verifying-an-Alien-Dictionary/README.md
- leetcode/901-1000/0953.Verifying-an-Alien-Dictionary/Solution.go
- leetcode/901-1000/0953.Verifying-an-Alien-Dictionary/Solution_test.go
Add solution and test-cases for problem 953
> Add solution and test-cases for problem 953

- leetcode/1001-1100/1071.Greatest-Common-Divisor-of-Strings/README.md
- leetcode/1001-1100/1071.Greatest-Common-Divisor-of-Strings/Solution.go
- leetcode/1001-1100/1071.Greatest-Common-Divisor-of-Strings/Solution_test.go
Add solution and test-cases for problem 1071
> Add solution and test-cases for problem 1071

- leetcode/1601-1700/1626.Best-Team-With-No-Conflicts/README.md
- leetcode/1601-1700/1626.Best-Team-With-No-Conflicts/Solution.go
- leetcode/1601-1700/1626.Best-Team-With-No-Conflicts/Solution_test.go
Add solution and test-cases for problem 1626
> Add solution and test-cases for problem 1626

- leetcode/401-500/0460.LFU-Cache/README.md
- leetcode/401-500/0460.LFU-Cache/Solution.go
- leetcode/401-500/0460.LFU-Cache/Solution_test.go
Add solution and test-cases for problem 460
> Add solution and test-cases for problem 460

- leetcode/301-400/0352.Data-Stream-as-Disjoint-Intervals/README.md
- leetcode/301-400/0352.Data-Stream-as-Disjoint-Intervals/Solution.go
- leetcode/301-400/0352.Data-Stream-as-Disjoint-Intervals/Solution_test.go
Add solution and test-cases for problem 352
> Add solution and test-cases for problem 352

- leetcode/401-500/0472.Concatenated-Words/README.md
- leetcode/401-500/0472.Concatenated-Words/Solution.go
- leetcode/401-500/0472.Concatenated-Words/Solution_test.go
Add solution and test-cases for problem 472
> Add solution and test-cases for problem 472

- leetcode/901-1000/0921.Minimum-Add-to-Make-Parentheses-Valid/README.md
- leetcode/901-1000/0921.Minimum-Add-to-Make-Parentheses-Valid/Solution.go
- leetcode/901-1000/0921.Minimum-Add-to-Make-Parentheses-Valid/Solution_test.go
Add solution and test-cases for problem 921
> Add solution and test-cases for problem 921

- leetcode/401-500/0494.Target-Sum/README.md
- leetcode/401-500/0494.Target-Sum/Solution.go
- leetcode/401-500/0494.Target-Sum/Solution_test.go
Add solution and test-cases for problem 494
> Add solution and test-cases for problem 494

- leetcode/1101-1200/1129.Shortest-Path-with-Alternating-Colors/README.md
- leetcode/1101-1200/1129.Shortest-Path-with-Alternating-Colors/Solution.go
- leetcode/1101-1200/1129.Shortest-Path-with-Alternating-Colors/Solution_test.go
Add solution and test-cases for problem 1129
> Add solution and test-cases for problem 1129

- leetcode/2301-2400/2306.Naming-a-Company/README.md
- leetcode/2301-2400/2306.Naming-a-Company/Solution.go
- leetcode/2301-2400/2306.Naming-a-Company/Solution_test.go
Add solution and test-cases for problem 2306
> Add solution and test-cases for problem 2306

- leetcode/401-500/0413.Arithmetic-Slices/README.md
- leetcode/401-500/0413.Arithmetic-Slices/Solution.go
- leetcode/401-500/0413.Arithmetic-Slices/Solution_test.go
Add solution and test-cases for problem 413
> Add solution and test-cases for problem 413

- leetcode/301-400/0343.Integer-Break/README.md
- leetcode/301-400/0343.Integer-Break/Solution.go
- leetcode/301-400/0343.Integer-Break/Solution_test.go
Add solution and test-cases for problem 343
> Add solution and test-cases for problem 343

- leetcode/301-400/0397.Integer-Replacement/README.md
- leetcode/301-400/0397.Integer-Replacement/Solution.go
- leetcode/301-400/0397.Integer-Replacement/Solution_test.go
Add solution and test-cases for problem 397
> Add solution and test-cases for problem 397

- leetcode/1501-1600/1523.Count-Odd-Numbers-in-an-Interval-Range/README.md
- leetcode/1501-1600/1523.Count-Odd-Numbers-in-an-Interval-Range/Solution.go
- leetcode/1501-1600/1523.Count-Odd-Numbers-in-an-Interval-Range/Solution_test.go
Add solution and test-cases for problem 1523
> Add solution and test-cases for problem 1523

- leetcode/1401-1500/1472.Design-Browser-History/README.md
- leetcode/1401-1500/1472.Design-Browser-History/Solution.go
- leetcode/1401-1500/1472.Design-Browser-History/Solution_test.go
Add solution and test-cases for problem 1472
> Add solution and test-cases for problem 1472

- leetcode/301-400/0306.Additive-Number/README.md
- leetcode/301-400/0306.Additive-Number/Solution.go
- leetcode/301-400/0306.Additive-Number/Solution_test.go
Add solution and test-cases for problem 306
> Add solution and test-cases for problem 306

- leetcode/401-500/0449.Serialize-and-Deserialize-BST/README.md
- leetcode/401-500/0449.Serialize-and-Deserialize-BST/Solution.go
- leetcode/401-500/0449.Serialize-and-Deserialize-BST/Solution_test.go
Add solution and test-cases for problem 449
> Add solution and test-cases for problem 449

- leetcode/2101-2200/2187.Minimum-Time-to-Complete-Trips/README.md
- leetcode/2101-2200/2187.Minimum-Time-to-Complete-Trips/Solution.go
- leetcode/2101-2200/2187.Minimum-Time-to-Complete-Trips/Solution_test.go
Add solution and test-cases for problem 2187
> Add solution and test-cases for problem 2187

- leetcode/1501-1600/1539.Kth-Missing-Positive-Number/README.md
- leetcode/1501-1600/1539.Kth-Missing-Positive-Number/Solution.go
- leetcode/1501-1600/1539.Kth-Missing-Positive-Number/Solution_test.go
Add solution and test-cases for problem 1539
> Add solution and test-cases for problem 1539

- leetcode/401-500/0443.String-Compression/README.md
- leetcode/401-500/0443.String-Compression/Solution.go
- leetcode/401-500/0443.String-Compression/Solution_test.go
Add solution and test-cases for problem 443
> Add solution and test-cases for problem 443

- leetcode/1201-1300/1247.Minimum-Swaps-to-Make-Strings-Equal/README.md
- leetcode/1201-1300/1247.Minimum-Swaps-to-Make-Strings-Equal/Solution.go
- leetcode/1201-1300/1247.Minimum-Swaps-to-Make-Strings-Equal/Solution_test.go
Add solution and test-cases for problem 1247
> Add solution and test-cases for problem 1247

- leetcode/2401-2500/2405.Optimal-Partition-of-String/README.md
- leetcode/2401-2500/2405.Optimal-Partition-of-String/Solution.go
- leetcode/2401-2500/2405.Optimal-Partition-of-String/Solution_test.go
Add solution and test-cases for problem 2405
> Add solution and test-cases for problem 2405

- leetcode/2401-2500/2439.Minimize-Maximum-of-Array/README.md
- leetcode/2401-2500/2439.Minimize-Maximum-of-Array/Solution.go
- leetcode/2401-2500/2439.Minimize-Maximum-of-Array/Solution_test.go
Add solution and test-cases for problem 2439
> Add solution and test-cases for problem 2439

- leetcode/2201-2300/2300.Successful-Pairs-of-Spells-and-Potions/README.md
- leetcode/2201-2300/2300.Successful-Pairs-of-Spells-and-Potions/Solution.go
- leetcode/2201-2300/2300.Successful-Pairs-of-Spells-and-Potions/Solution_test.go
Add solution and test-cases for problem 2300
> Add solution and test-cases for problem 2300

- leetcode/1601-1700/1639.Number-of-Ways-to-Form-a-Target-String-Given-a-Dictionary/README.md
- leetcode/1601-1700/1639.Number-of-Ways-to-Form-a-Target-String-Given-a-Dictionary/Solution.go
- leetcode/1601-1700/1639.Number-of-Ways-to-Form-a-Target-String-Given-a-Dictionary/Solution_test.go
Add solution and test-cases for problem 1639
> Add solution and test-cases for problem 1639

- leetcode/1001-1100/1072.Flip-Columns-For-Maximum-Number-of-Equal-Rows/README.md
- leetcode/1001-1100/1072.Flip-Columns-For-Maximum-Number-of-Equal-Rows/Solution.go
- leetcode/1001-1100/1072.Flip-Columns-For-Maximum-Number-of-Equal-Rows/Solution_test.go
Add solution and test-cases for problem 1072
> Add solution and test-cases for problem 1072

- leetcode/2401-2500/2466.Count-Ways-To-Build-Good-Strings/README.md
- leetcode/2401-2500/2466.Count-Ways-To-Build-Good-Strings/Solution.go
- leetcode/2401-2500/2466.Count-Ways-To-Build-Good-Strings/Solution_test.go
Add solution and test-cases for problem 2466
> Add solution and test-cases for problem 2466

- leetcode/801-900/0898.Bitwise-ORs-of-Subarrays/README.md
- leetcode/801-900/0898.Bitwise-ORs-of-Subarrays/Solution.go
- leetcode/801-900/0898.Bitwise-ORs-of-Subarrays/Solution_test.go
Add solution and test-cases for problem 898
> Add solution and test-cases for problem 898

- leetcode/1401-1500/1456.Maximum-Number-of-Vowels-in-a-Substring-of-Given-Length/README.md
- leetcode/1401-1500/1456.Maximum-Number-of-Vowels-in-a-Substring-of-Given-Length/Solution.go
- leetcode/1401-1500/1456.Maximum-Number-of-Vowels-in-a-Substring-of-Given-Length/Solution_test.go
Add solution and test-cases for problem 1456
> Add solution and test-cases for problem 1456

- leetcode/2201-2300/2215.Find-the-Difference-of-Two-Arrays/README.md
- leetcode/2201-2300/2215.Find-the-Difference-of-Two-Arrays/Solution.go
- leetcode/2201-2300/2215.Find-the-Difference-of-Two-Arrays/Solution_test.go
Add solution and test-cases for problem 2215
> Add solution and test-cases for problem 2215

- leetcode/1801-1900/1822.Sign-of-the-Product-of-an-Array/README.md
- leetcode/1801-1900/1822.Sign-of-the-Product-of-an-Array/Solution.go
- leetcode/1801-1900/1822.Sign-of-the-Product-of-an-Array/Solution_test.go
Add solution and test-cases for problem 1822
> Add solution and test-cases for problem 1822

- leetcode/1401-1500/1491.Average-Salary-Excluding-the-Minimum-and-Maximum-Salary/README.md
- leetcode/1401-1500/1491.Average-Salary-Excluding-the-Minimum-and-Maximum-Salary/Solution.go
- leetcode/1401-1500/1491.Average-Salary-Excluding-the-Minimum-and-Maximum-Salary/Solution_test.go
Add solution and test-cases for problem 1491
> Add solution and test-cases for problem 1491

- leetcode/801-900/0839.Similar-String-Groups/README.md
- leetcode/801-900/0839.Similar-String-Groups/Solution.go
- leetcode/801-900/0839.Similar-String-Groups/Solution_test.go
Add solution and test-cases for problem 839
> Add solution and test-cases for problem 839

- leetcode/2301-2400/2336.Smallest-Number-in-Infinite-Set/README.md
- leetcode/2301-2400/2336.Smallest-Number-in-Infinite-Set/Solution.go
- leetcode/2301-2400/2336.Smallest-Number-in-Infinite-Set/Solution_test.go
Add solution and test-cases for problem 2336
> Add solution and test-cases for problem 2336

- leetcode/1401-1500/1416.Restore-The-Array/README.md
- leetcode/1401-1500/1416.Restore-The-Array/Solution.go
- leetcode/1401-1500/1416.Restore-The-Array/Solution_test.go
Add solution and test-cases for problem 1416
> Add solution and test-cases for problem 1416

- leetcode/1701-1800/1774.Closest-Dessert-Cost/README.md
- leetcode/1701-1800/1774.Closest-Dessert-Cost/Solution.go
- leetcode/1701-1800/1774.Closest-Dessert-Cost/Solution_test.go
Add solution and test-cases for problem 1774
> Add solution and test-cases for problem 1774

- leetcode/1301-1400/1312.Minimum-Insertion-Steps-to-Make-a-String-Palindrome/README.md
- leetcode/1301-1400/1312.Minimum-Insertion-Steps-to-Make-a-String-Palindrome/Solution.go
- leetcode/1301-1400/1312.Minimum-Insertion-Steps-to-Make-a-String-Palindrome/Solution_test.go
Add solution and test-cases for problem 1312
> Add solution and test-cases for problem 1312

- leetcode/901-1000/0956.Tallest-Billboard/README.md
- leetcode/901-1000/0956.Tallest-Billboard/Solution.go
- leetcode/901-1000/0956.Tallest-Billboard/Solution_test.go
Add solution and test-cases for problem 956
> Add solution and test-cases for problem 956

- leetcode/1501-1600/1561.Maximum-Number-of-Coins-You-Can-Get/README.md
- leetcode/1501-1600/1561.Maximum-Number-of-Coins-You-Can-Get/Solution.go
- leetcode/1501-1600/1561.Maximum-Number-of-Coins-You-Can-Get/Solution_test.go
Add solution and test-cases for problem 1561
> Add solution and test-cases for problem 1561

- leetcode/1001-1100/1027.Longest-Arithmetic-Sequence/README.md
- leetcode/1001-1100/1027.Longest-Arithmetic-Sequence/Solution.go
- leetcode/1001-1100/1027.Longest-Arithmetic-Sequence/Solution_test.go
Add solution and test-cases for problem 1027
> Add solution and test-cases for problem 1027

- leetcode/1501-1600/1575.Count-All-Possible-Routes/README.md
- leetcode/1501-1600/1575.Count-All-Possible-Routes/Solution.go
- leetcode/1501-1600/1575.Count-All-Possible-Routes/Solution_test.go
Add solution and test-cases for problem 1575
> Add solution and test-cases for problem 1575

- leetcode/1101-1200/1146.Snapshot-Array/README.md
- leetcode/1101-1200/1146.Snapshot-Array/Solution.go
- leetcode/1101-1200/1146.Snapshot-Array/Solution_test.go
Add solution and test-cases for problem 1146
> Add solution and test-cases for problem 1146

- leetcode/2301-2400/2391.Minimum-Amount-of-Time-to-Collect-Garbage/README.md
- leetcode/2301-2400/2391.Minimum-Amount-of-Time-to-Collect-Garbage/Solution.go
- leetcode/2301-2400/2391.Minimum-Amount-of-Time-to-Collect-Garbage/Solution_test.go
Add solution and test-cases for problem 2391
> Add solution and test-cases for problem 2391

- leetcode/2401-2500/2448.Minimum-Cost-to-Make-Array-Equal/README.md
- leetcode/2401-2500/2448.Minimum-Cost-to-Make-Array-Equal/Solution.go
- leetcode/2401-2500/2448.Minimum-Cost-to-Make-Array-Equal/Solution_test.go
Add solution and test-cases for problem 2448
> Add solution and test-cases for problem 2448

- leetcode/701-800/0744.Find-Smallest-Letter-Greater-Than-Target/README.md
- leetcode/701-800/0744.Find-Smallest-Letter-Greater-Than-Target/Solution.go
- leetcode/701-800/0744.Find-Smallest-Letter-Greater-Than-Target/Solution_test.go
Add solution and test-cases for problem 744
> Add solution and test-cases for problem 744

- leetcode/1301-1400/1396.Design-Underground-System/README.md
- leetcode/1301-1400/1396.Design-Underground-System/Solution.go
- leetcode/1301-1400/1396.Design-Underground-System/Solution_test.go
Add solution and test-cases for proble 1396
> Add solution and test-cases for proble 1396

- leetcode/701-800/0705.Design-HashSet/README.md
- leetcode/701-800/0705.Design-HashSet/Solution.go
- leetcode/701-800/0705.Design-HashSet/Solution_test.go
Add solution and test-cases for problem 705
> Add solution and test-cases for problem 705

- leetcode/301-400/0347.Top-K-Frequent-Elements/README.md
- leetcode/301-400/0347.Top-K-Frequent-Elements/Solution.go
- leetcode/301-400/0347.Top-K-Frequent-Elements/Solution_test.go
Add solution and test-cases for problem 347
> Add solution and test-cases for problem 347

- leetcode/1401-1500/1476.Subrectangle-Queries/README.md
- leetcode/1401-1500/1476.Subrectangle-Queries/Solution.go
- leetcode/1401-1500/1476.Subrectangle-Queries/Solution_test.go
Add solution and test-cases for problem 1476
> Add solution and test-cases for problem 1476

- leetcode/1601-1700/1603.Design-Parking-System/README.md
- leetcode/1601-1700/1603.Design-Parking-System/Solution.go
- leetcode/1601-1700/1603.Design-Parking-System/Solution_test.go
Add solution and test-cases for problem 1603
> Add solution and test-cases for problem 1603

- leetcode/301-400/0399.Evaluate-Division/README.md
- leetcode/301-400/0399.Evaluate-Division/Solution.go
- leetcode/301-400/0399.Evaluate-Division/Solution_test.go
Add solution and test-cases for problem 399
> Add solution and test-cases for problem 399

- leetcode/901-1000/0934.Shortest-Bridge/README.md
- leetcode/901-1000/0934.Shortest-Bridge/Solution.go
- leetcode/901-1000/0934.Shortest-Bridge/Solution_test.go
Add solution and test-cases for problem 934
> Add solution and test-cases for problem 934

- leetcode/2001-2100/2079.Watering-Plants/README.md
- leetcode/2001-2100/2079.Watering-Plants/Solution.go
- leetcode/2001-2100/2079.Watering-Plants/Solution_test.go
Add solution and test-cases for problem 2079
> Add solution and test-cases for problem 2079

- leetcode/1801-1900/1877.Minimize-Maximum-Pair-Sum-in-Array/README.md
- leetcode/1801-1900/1877.Minimize-Maximum-Pair-Sum-in-Array/Solution.go
- leetcode/1801-1900/1877.Minimize-Maximum-Pair-Sum-in-Array/Solution_test.go
Add solution and test-cases for problem 1877
> Add solution and test-cases for problem 1877

- leetcode/1501-1600/1551.Minimum-Operations-to-Make-Array-Equal/README.md
- leetcode/1501-1600/1551.Minimum-Operations-to-Make-Array-Equal/Solution.go
- leetcode/1501-1600/1551.Minimum-Operations-to-Make-Array-Equal/Solution_test.go
Add solution and test-cases for problem 1551
> Add solution and test-cases for problem 1551

- leetcode/801-900/0895.Maximum-Frequency-Stack/README.md
- leetcode/801-900/0895.Maximum-Frequency-Stack/Solution.go
- leetcode/801-900/0895.Maximum-Frequency-Stack/Solution_test.go
Add solution and test-cases for problem 895
> Add solution and test-cases for problem 895

- leetcode/2301-2400/2305.Fair-Distribution-of-Cookies/README.md
- leetcode/2301-2400/2305.Fair-Distribution-of-Cookies/Solution.go
- leetcode/2301-2400/2305.Fair-Distribution-of-Cookies/Solution_test.go
Add solution and test-cases for problem 2305
> Add solution and test-cases for problem 2305

- leetcode/801-900/0859.Buddy-Strings/README.md
- leetcode/801-900/0859.Buddy-Strings/Solution.go
- leetcode/801-900/0859.Buddy-Strings/Solution_test.go
Add solution and test-cases for problem 859
> Add solution and test-cases for problem 859

- leetcode/1401-1500/1493.LongestSubarray-of-1s-After-Deleting-One-Element/README.md
- leetcode/1401-1500/1493.LongestSubarray-of-1s-After-Deleting-One-Element/Solution.go
- leetcode/1401-1500/1493.LongestSubarray-of-1s-After-Deleting-One-Element/Solution_test.go
Add solution and test-cases for problem 1493
> Add solution and test-cases for problem 1493

- leetcode/701-800/0712.Minimum-ASCII-Delete-Sum-for-Two-Strings/README.md
- leetcode/701-800/0712.Minimum-ASCII-Delete-Sum-for-Two-Strings/Solution.go
- leetcode/701-800/0712.Minimum-ASCII-Delete-Sum-for-Two-Strings/Solution_test.go
Add solution and test-cases for problem 712
> Add solution and test-cases for problem 712

- leetcode/2001-2100/2024.Maximize-the-Confusion-of-an-Exam/README.md
- leetcode/2001-2100/2024.Maximize-the-Confusion-of-an-Exam/Solution.go
- leetcode/2001-2100/2024.Maximize-the-Confusion-of-an-Exam/Solution_test.go
Add solution and test-cases for problem 2024
> Add solution and test-cases for problem 2024

- leetcode/701-800/0731.My-Calendar-II/README.md
- leetcode/701-800/0731.My-Calendar-II/Solution.go
- leetcode/701-800/0731.My-Calendar-II/Solution_test.go
Add solution and test-cases for problem 731
> Add solution and test-cases for problem 731

- leetcode/701-800/0732.My-Calendar-III/README.md
- leetcode/701-800/0732.My-Calendar-III/Solution.go
- leetcode/701-800/0732.My-Calendar-III/Solution_test.go
Add solution and test-cases for problem 732
> Add solution and test-cases for problem 732

- leetcode/1801-1900/1870.Minimum-Speed-to-Arrive-on-Time/README.md
- leetcode/1801-1900/1870.Minimum-Speed-to-Arrive-on-Time/Solution.go
- leetcode/1801-1900/1870.Minimum-Speed-to-Arrive-on-Time/Solution_test.go
Add solution and test-cases for problem 1870
> Add solution and test-cases for problem 1870

- leetcode/801-900/0852.Peak-Index-in-a-Mountain-Array/README.md
- leetcode/801-900/0852.Peak-Index-in-a-Mountain-Array/Solution.go
- leetcode/801-900/0852.Peak-Index-in-a-Mountain-Array/Solution_test.go
Add solution and test-cases for problem 852
> Add solution and test-cases for problem 852

- leetcode/701-800/0735.Asteroid-Collision/README.md
- leetcode/701-800/0735.Asteroid-Collision/Solution.go
- leetcode/701-800/0735.Asteroid-Collision/Solution_test.go
Add solution and test-cases for problem 735
> Add solution and test-cases for problem 735

- leetcode/1101-1200/1125.Smallest-Sufficient-Team/README.md
- leetcode/1101-1200/1125.Smallest-Sufficient-Team/Solution.go
- leetcode/1101-1200/1125.Smallest-Sufficient-Team/Solution_test.go
Add solution and test-cases for problem 1125
> Add solution and test-cases for problem 1125

- leetcode/101-200/0114.Flatten-Binary-Tree-to-Linked-List/Solution.go
- leetcode/101-200/0114.Flatten-Binary-Tree-to-Linked-List/Solution_test.go
Add solution and test-cases for problem 114
> Add solution and test-cases for problem 114

- leetcode/1101-1200/1108.Defanging-an-IP-Address/README.md
- leetcode/1101-1200/1108.Defanging-an-IP-Address/Solution.go
- leetcode/1101-1200/1108.Defanging-an-IP-Address/Solution_test.go
Add solution and test-cases for problem 1108
> Add solution and test-cases for problem 1108

- leetcode/1201-1300/1218.Longest-Arithmetic-Subsequence-of-Given-Difference/README.md
- leetcode/1201-1300/1218.Longest-Arithmetic-Subsequence-of-Given-Difference/Solution.go
- leetcode/1201-1300/1218.Longest-Arithmetic-Subsequence-of-Given-Difference/Solution_test.go
Add solution and test-cases for problem 1218
> Add solution and test-cases for problem 1218

- leetcode/201-300/0207.Course-Schedule/README.md
- leetcode/201-300/0207.Course-Schedule/Solution.go
- leetcode/201-300/0207.Course-Schedule/Solution_test.go
Add solution and test-cases for problem 207
> Add solution and test-cases for problem 207

- leetcode/801-900/0899.Orderly-Queue/README.md
- leetcode/801-900/0899.Orderly-Queue/Solution.go
- leetcode/801-900/0899.Orderly-Queue/Solution_test.go
Add solution and test-cases for problem 899
> Add solution and test-cases for problem 899

- leetcode/1901-2000/1920.Build-Array-from-Permutation/README.md
- leetcode/1901-2000/1920.Build-Array-from-Permutation/Solution.go
- leetcode/1901-2000/1920.Build-Array-from-Permutation/Solution_test.go
Add solution and test-cases for problem 1920
> Add solution and test-cases for problem 1920

- leetcode/401-500/0459.Repeated-Substring-Pattern/README.md
- leetcode/401-500/0459.Repeated-Substring-Pattern/Solution.go
- leetcode/401-500/0459.Repeated-Substring-Pattern/Solution_test.go
Add solution and test-cases for problem 459
> Add solution and test-cases for problem 459

- leetcode/201-300/0239.Sliding-Window-Maximum/README.md
- leetcode/201-300/0239.Sliding-Window-Maximum/Solution.go
- leetcode/201-300/0239.Sliding-Window-Maximum/Solution_test.go
Add solution and test-cases for problem 239
> Add solution and test-cases for problem 239

- leetcode/201-300/0210.Course-Schedule-II/README.md
- leetcode/201-300/0210.Course-Schedule-II/Solution.go
- leetcode/201-300/0210.Course-Schedule-II/Solution_test.go
Add solution and test-cases for problem 210
> Add solution and test-cases for problem 210

- leetcode/201-300/0287.Find-the-Duplicate-Number/README.md
- leetcode/201-300/0287.Find-the-Duplicate-Number/Solution.go
- leetcode/201-300/0287.Find-the-Duplicate-Number/Solution_test.go
Add solution and update readme for problem 287
> Add solution and update readme for problem 287

- leetcode/1501-1600/1508.Range-Sum-of-Sorted-Subarray-Sums/README.md
- leetcode/1501-1600/1508.Range-Sum-of-Sorted-Subarray-Sums/Solution.go
- leetcode/1501-1600/1508.Range-Sum-of-Sorted-Subarray-Sums/Solution_test.go
Add solution and test-cases for problem 1508
> Add solution and test-cases for problem 1508

- leetcode/201-300/0241.Different-Ways-to-Add-Parentheses/Solution.go
- leetcode/201-300/0241.Different-Ways-to-Add-Parentheses/Solution_test.go
Add solution and test-cases for problem 241
> Add solution and test-cases for problem 241

- leetcode/101-200/0166.Fraction-to-Recurring-Decimal/README.md
- leetcode/101-200/0166.Fraction-to-Recurring-Decimal/Solution.go
- leetcode/101-200/0166.Fraction-to-Recurring-Decimal/Solution_test.go
Add solution and test-cases for problem 166
> Add solution and test-cases for problem 166

- leetcode/2301-2400/2369.Check-if-There-is-a-Valid-Partition-For-The-Array/README.md
- leetcode/2301-2400/2369.Check-if-There-is-a-Valid-Partition-For-The-Array/Solution.go
- leetcode/2301-2400/2369.Check-if-There-is-a-Valid-Partition-For-The-Array/Solution_test.go
Add solution and test-cases for problem 2369
> Add solution and test-cases for problem 2369

- leetcode/101-200/0168.Excel-Sheet-Column-Title/README.md
- leetcode/101-200/0168.Excel-Sheet-Column-Title/Solution.go
- leetcode/101-200/0168.Excel-Sheet-Column-Title/Solution_test.go
Add solution and test-cases for problem 168
> Add solution and test-cases for problem 168

- leetcode/1-100/0004.Median-of-Two-Sorted-Arrays/Solution.go
- leetcode/1-100/0004.Median-of-Two-Sorted-Arrays/Solution_test.go
> Add solution for problem 4

- leetcode/1301-1400/1387.Sort-Integers-by-The-Power-Value/README.md
- leetcode/1301-1400/1387.Sort-Integers-by-The-Power-Value/Solution.go
- leetcode/1301-1400/1387.Sort-Integers-by-The-Power-Value/Solution_test.go
Add solution, readme and test-cases for problem 1387
> Add solution, readme and test-cases for problem 1387

- leetcode/701-800/0720.Longest-Word-in-Dictionary/README.md
- leetcode/701-800/0720.Longest-Word-in-Dictionary/Solution.go
- leetcode/701-800/0720.Longest-Word-in-Dictionary/Solution_test.go
Add solution and test-cases for problem 720
> Add solution and test-cases for problem 720

- leetcode/2101-2200/2131.Longest-Palindrome-by-Concatenating-Two-Letter-Words/README.md
- leetcode/2101-2200/2131.Longest-Palindrome-by-Concatenating-Two-Letter-Words/Solution.go
- leetcode/2101-2200/2131.Longest-Palindrome-by-Concatenating-Two-Letter-Words/Solution_test.go
Add solution and test-cases for problem 2131
> Add solution and test-cases for problem 2131

- leetcode/201-300/0229.Majority-Element-II/README.md
- leetcode/201-300/0229.Majority-Element-II/Solution.go
- leetcode/201-300/0229.Majority-Element-II/Solution_test.go
Add solution and test-cases for problem 229
> Add solution and test-cases for problem 229

- leetcode/1301-1400/1359.Count-All-Valid-Pickup-and-Delivery-Options/README.md
- leetcode/1301-1400/1359.Count-All-Valid-Pickup-and-Delivery-Options/Solution.go
- leetcode/1301-1400/1359.Count-All-Valid-Pickup-and-Delivery-Options/Solution_test.go
Add solution and test-cases for problem 1359
> Add solution and test-cases for problem 1359

- leetcode/501-600/0526.Beautiful-Arrangement/README.md
- leetcode/501-600/0526.Beautiful-Arrangement/Solution.go
- leetcode/501-600/0526.Beautiful-Arrangement/Solution_test.go
Add solution and test-cases for problem 526
> Add solution and test-cases for problem 526

- leetcode/301-400/0377.Combination-Sum-IV/Solution.go
- leetcode/301-400/0377.Combination-Sum-IV/Solution_test.go
> Add solution for problem 377

- leetcode/2701-2800/2707.Extra-Characters-in-a-String/README.md
- leetcode/2701-2800/2707.Extra-Characters-in-a-String/Solution.go
- leetcode/2701-2800/2707.Extra-Characters-in-a-String/Solution_test.go
Add solution and test-cases for problem 2707
> Add solution and test-cases for problem 2707

- leetcode/2401-2500/2483.Minimum-Penalty-for-a-Shop/README.md
- leetcode/2401-2500/2483.Minimum-Penalty-for-a-Shop/Solution.go
- leetcode/2401-2500/2483.Minimum-Penalty-for-a-Shop/Solution_test.go
Add solution and test-cases for problem 2483
> Add solution and test-cases for problem 2483

- leetcode/201-300/0225.Implement-Stack-using-Queues/Solution.go
- leetcode/201-300/0225.Implement-Stack-using-Queues/Solution_test.go
Add solution and test-cases for problem 225
> Add solution and test-cases for problem 225

- leetcode/701-800/0767.Reorganize-String/README.md
- leetcode/701-800/0767.Reorganize-String/Solution.go
- leetcode/701-800/0767.Reorganize-String/Solution_test.go
Add solution and test-cases for problem 767
> Add solution and test-cases for problem 767

- leetcode/601-700/0646.Maximum-Length-of-Pair-Chain/README.md
- leetcode/601-700/0646.Maximum-Length-of-Pair-Chain/Solution.go
- leetcode/601-700/0646.Maximum-Length-of-Pair-Chain/Solution_test.go
Add solution and test-cases for problem 646
> Add solution and test-cases for problem 646

- leetcode/401-500/0403.Frog-Jump/README.md
- leetcode/401-500/0403.Frog-Jump/Solution.go
- leetcode/401-500/0403.Frog-Jump/Solution_test.go
Add solution and test-cases for problem 403
> Add solution and test-cases for problem 403

- leetcode/401-500/0424.Longest-Repeating-Character-Replacement/README.md
- leetcode/401-500/0424.Longest-Repeating-Character-Replacement/Solution.go
- leetcode/401-500/0424.Longest-Repeating-Character-Replacement/Solution_test.go
Add solution and test-cases for problem 424
> Add solution and test-cases for problem 424

- leetcode/1001-1100/1081.Smallest-Subsequence-of-Distinct-Characters/README.md
- leetcode/1001-1100/1081.Smallest-Subsequence-of-Distinct-Characters/Solution.go
- leetcode/1001-1100/1081.Smallest-Subsequence-of-Distinct-Characters/Solution_test.go
Add solution and test-cases for problem 1081
> Add solution and test-cases for problem 1081

- leetcode/301-400/0316.Remove-Duplicate-Letters/README.md
- leetcode/301-400/0316.Remove-Duplicate-Letters/Solution.go
- leetcode/301-400/0316.Remove-Duplicate-Letters/Solution_test.go
Add solution and test-cases for problem 316
> Add solution and test-cases for problem 316

- leetcode/601-700/0609.Find-Duplicate-File-in-System/README.md
- leetcode/601-700/0609.Find-Duplicate-File-in-System/Solution.go
- leetcode/601-700/0609.Find-Duplicate-File-in-System/Solution_test.go
Add solution and test-cases for problem 609
> Add solution and test-cases for problem 609

- leetcode/801-900/0880.Decoded-String-at-Index/README.md
- leetcode/801-900/0880.Decoded-String-at-Index/Solution.go
- leetcode/801-900/0880.Decoded-String-at-Index/Solution_test.go
Add solution and test-cases for problem 880
> Add solution and test-cases for problem 880

- leetcode/301-400/0394.Decode-String/README.md
- leetcode/301-400/0394.Decode-String/Solution.go
- leetcode/301-400/0394.Decode-String/Solution_test.go
Add solution and test-cases for problem 394
> Add solution and test-cases for problem 394

- leetcode/1201-1300/1202.Smallest-String-With-Swaps/README.md
- leetcode/1201-1300/1202.Smallest-String-With-Swaps/Solution.go
- leetcode/1201-1300/1202.Smallest-String-With-Swaps/Solution_test.go
Add solution and test-cases for problem 1202
> Add solution and test-cases for problem 1202

- leetcode/701-800/0779.K-th-Symbol-in-Grammar/README.md
- leetcode/701-800/0779.K-th-Symbol-in-Grammar/Solution.go
- leetcode/701-800/0779.K-th-Symbol-in-Grammar/Solution_test.go
Add solution and test-cases for problem 779
> Add solution and test-cases for problem 779

- leetcode/1701-1800/1793.Maximum-Score-of-a-Good-Subarray/README.md
- leetcode/1701-1800/1793.Maximum-Score-of-a-Good-Subarray/Solution.go
- leetcode/1701-1800/1793.Maximum-Score-of-a-Good-Subarray/Solution_test.go
Add solution and test-cases for problem 1793
> Add solution and test-cases for problem 1793

- leetcode/2401-2500/2442.Count-Number-of-Distinct-Integers-After-Reverse-Operations/README.md
- leetcode/2401-2500/2442.Count-Number-of-Distinct-Integers-After-Reverse-Operations/Solution.go
- leetcode/2401-2500/2442.Count-Number-of-Distinct-Integers-After-Reverse-Operations/Solution_test.go
Add solution and test-cases for problem 2442
> Add solution and test-cases for problem 2442

- leetcode/2501-2600/2530.Maximal-Score-After-Applying-K-Operations/README.md
- leetcode/2501-2600/2530.Maximal-Score-After-Applying-K-Operations/Solution.go
- leetcode/2501-2600/2530.Maximal-Score-After-Applying-K-Operations/Solution_test.go
Add solution and test-cases for problem 2530
> Add solution and test-cases for problem 2530

- leetcode/1201-1300/1269.Number-of-Ways-to-Stay-in-the-Same-Place-After-Some-Steps/README.md
- leetcode/1201-1300/1269.Number-of-Ways-to-Stay-in-the-Same-Place-After-Some-Steps/Solution.go
- leetcode/1201-1300/1269.Number-of-Ways-to-Stay-in-the-Same-Place-After-Some-Steps/Solution_test.go
Add solution and test-cases for problem 1269
> Add solution and test-cases for problem 1269

- leetcode/1001-1100/1095.Find-in-Mountain-Array/README.md
- leetcode/1001-1100/1095.Find-in-Mountain-Array/Solution.go
- leetcode/1001-1100/1095.Find-in-Mountain-Array/Solution_test.go
Add solution and test-cases for problem 1095
> Add solution and test-cases for problem 1095

- leetcode/2701-2800/2731.Movement-of-Robots/README.md
- leetcode/2701-2800/2731.Movement-of-Robots/Solution.go
- leetcode/2701-2800/2731.Movement-of-Robots/Solution_test.go
Add solution and test-cases for problem 2731
> Add solution and test-cases for problem 2731

- leetcode/1301-1400/1358.Number-of-Substrings-Containing-All-Three-Characters/README.md
- leetcode/1301-1400/1358.Number-of-Substrings-Containing-All-Three-Characters/Solution.go
- leetcode/1301-1400/1358.Number-of-Substrings-Containing-All-Three-Characters/Solution_test.go
Add solution and test-cases for problem 1358
> Add solution and test-cases for problem 1358

- leetcode/1401-1500/1458.Max-Dot-Product-of-Two-Subsequences/README.md
- leetcode/1401-1500/1458.Max-Dot-Product-of-Two-Subsequences/Solution.go
- leetcode/1401-1500/1458.Max-Dot-Product-of-Two-Subsequences/Solution_test.go
Add solution and test-cases for problem 1458
> Add solution and test-cases for problem 1458

- leetcode/1201-1300/1239.Maximum-Length-of-a-Concatenated-String-with-Unique-Characters/README.md
- leetcode/1201-1300/1239.Maximum-Length-of-a-Concatenated-String-with-Unique-Characters/Solution.go
- leetcode/1201-1300/1239.Maximum-Length-of-a-Concatenated-String-with-Unique-Characters/Solution_test.go
Add solution and test-cases for problem 1239
> Add solution and test-cases for problem 1239

- leetcode/701-800/0706.Design-HashMap/README.md
- leetcode/701-800/0706.Design-HashMap/Solution.go
- leetcode/701-800/0706.Design-HashMap/Solution_test.go
Add solution and test-cases for problem 706
> Add solution and test-cases for problem 706

- leetcode/301-400/0355.Design-Twitter/README.md
- leetcode/301-400/0355.Design-Twitter/Solution.go
- leetcode/301-400/0355.Design-Twitter/Solution_test.go
Add solution and test-cases for problem 355
> Add solution and test-cases for problem 355

- leetcode/2001-2100/2038.Remove-Colored-Pieces-if-Both-Neighbors-are-the-Same-Color/README.md
- leetcode/2001-2100/2038.Remove-Colored-Pieces-if-Both-Neighbors-are-the-Same-Color/Solution.go
- leetcode/2001-2100/2038.Remove-Colored-Pieces-if-Both-Neighbors-are-the-Same-Color/Solution_test.go
Add solution and test-cases for problem 2038
> Add solution and test-cases for problem 2038

- leetcode/401-500/0477.Total-Hamming-Distance/README.md
- leetcode/401-500/0477.Total-Hamming-Distance/Solution.go
- leetcode/401-500/0477.Total-Hamming-Distance/Solution_test.go
Add solution and test-cases for problem 477
> Add solution and test-cases for problem 477

- leetcode/401-500/0454.4Sum-II/README.md
- leetcode/401-500/0454.4Sum-II/Solution.go
- leetcode/401-500/0454.4Sum-II/Solution_test.go
Add solution and test-cases for problem 454
> Add solution and test-cases for problem 454

- leetcode/401-500/0442.Find-All-Duplicates-in-an-Array/README.md
- leetcode/401-500/0442.Find-All-Duplicates-in-an-Array/Solution.go
- leetcode/401-500/0442.Find-All-Duplicates-in-an-Array/Solution_test.go
Add solution and test-cases for problem 442
> Add solution and test-cases for problem 442

- leetcode/401-500/0456.132-Pattern/README.md
- leetcode/401-500/0456.132-Pattern/Solution.go
- leetcode/401-500/0456.132-Pattern/Solution_test.go
Add solution and test-cases for problem 456
> Add solution and test-cases for problem 456

- leetcode/201-300/0284.Peeking-Iterator/README.md
- leetcode/201-300/0284.Peeking-Iterator/Solution.go
- leetcode/201-300/0284.Peeking-Iterator/Solution_test.go
Add solution and test-cases for problem 284
> Add solution and test-cases for problem 284

- leetcode/201-300/0260.Single-Number-III/README.md
- leetcode/201-300/0260.Single-Number-III/Solution.go
- leetcode/201-300/0260.Single-Number-III/Solution_test.go
Add solution and test-cases for problem 260
> Add solution and test-cases for problem 260

- .github/workflows/test.yml
fix workflow that fails to execute
> fix workflow that fails to execute

- leetcode/1801-1900/1845.Seat-Reservation-Manager/README.md
- leetcode/1801-1900/1845.Seat-Reservation-Manager/Solution.go
- leetcode/1801-1900/1845.Seat-Reservation-Manager/Solution_test.go
Add solution and test-cases for problem 1845
> Add solution and test-cases for problem 1845

- leetcode/501-600/0503.Next-Greater-Element-II/README.md
- leetcode/501-600/0503.Next-Greater-Element-II/Solution.go
- leetcode/501-600/0503.Next-Greater-Element-II/Solution_test.go
Add solution and test-cases for problem 503
> Add solution and test-cases for problem 503

- leetcode/1501-1600/1535.Find-the-Winner-of-an-Array-Game/README.md
- leetcode/1501-1600/1535.Find-the-Winner-of-an-Array-Game/Solution.go
- leetcode/1501-1600/1535.Find-the-Winner-of-an-Array-Game/Solution_test.go
Add solution and test-cases for problem 1535
> Add solution and test-cases for problem 1535

- leetcode/1301-1400/1356.Sort-Integers-by-The-Number-of-1-Bits/README.md
- leetcode/1301-1400/1356.Sort-Integers-by-The-Number-of-1-Bits/Solution.go
- leetcode/1301-1400/1356.Sort-Integers-by-The-Number-of-1-Bits/Solution_test.go
Add solution and test-cases for problem 1356
> Add solution and test-cases for problem 1356

- leetcode/1901-2000/1921.Eliminate-Maximum-Number-of-Monsters/README.md
- leetcode/1901-2000/1921.Eliminate-Maximum-Number-of-Monsters/Solution.go
- leetcode/1901-2000/1921.Eliminate-Maximum-Number-of-Monsters/Solution_test.go
Add solution and test-cases for problem 1921
> Add solution and test-cases for problem 1921

- leetcode/1701-1800/1743.Restore-the-Array-From-Adjacent-Pairs/README.md
- leetcode/1701-1800/1743.Restore-the-Array-From-Adjacent-Pairs/Solution.go
- leetcode/1701-1800/1743.Restore-the-Array-From-Adjacent-Pairs/Solution_test.go
Add solution and test-cases for problem 1743
> Add solution and test-cases for problem 1743

- leetcode/801-900/0815.Bus-Routes/README.md
- leetcode/801-900/0815.Bus-Routes/Solution.go
- leetcode/801-900/0815.Bus-Routes/Solution_test.go
Add solution and test-cases for problem 815
> Add solution and test-cases for problem 815

- leetcode/2701-2800/2785.Sort-Vowels-in-a-String/README.md
- leetcode/2701-2800/2785.Sort-Vowels-in-a-String/Solution.go
- leetcode/2701-2800/2785.Sort-Vowels-in-a-String/Solution_test.go
Add solution and test-cases for problem 2785
> Add solution and test-cases for problem 2785

- leetcode/1701-1800/1759.Count-Number-of-Homogenous-Substrings/README.md
- leetcode/1701-1800/1759.Count-Number-of-Homogenous-Substrings/Solution.go
- leetcode/1701-1800/1759.Count-Number-of-Homogenous-Substrings/Solution_test.go
Add solution and test-cases for problem 1759
> Add solution and test-cases for problem 1759

- leetcode/2301-2400/2353.Design-a-Food-Rating-System/README.md
- leetcode/2301-2400/2353.Design-a-Food-Rating-System/Solution.go
- leetcode/2301-2400/2353.Design-a-Food-Rating-System/Solution_test.go
Add solution and test-cases for problem 2353
> Add solution and test-cases for problem 2353

- leetcode/1401-1500/1436.Destination-City/README.md
- leetcode/1401-1500/1436.Destination-City/Solution.go
- leetcode/1401-1500/1436.Destination-City/Solution_test.go
Add solution and test-cases for problem 1436
> Add solution and test-cases for problem 1436

- leetcode/101-200/0164.Maximum-Gap/README.md
- leetcode/101-200/0164.Maximum-Gap/Solution.go
- leetcode/101-200/0164.Maximum-Gap/Solution_test.go
Add solution and test-cases for problem 164
> Add solution and test-cases for problem 164

- leetcode/701-800/0754.Reach-a-Number/README.md
- leetcode/701-800/0754.Reach-a-Number/Solution.go
- leetcode/701-800/0754.Reach-a-Number/Solution_test.go
Add solution and test-cases for problem 754
> Add solution and test-cases for problem 754

- leetcode/401-500/0421.Maximum-XOR-of-Two-Numbers-in-an-Array/README.md
- leetcode/401-500/0421.Maximum-XOR-of-Two-Numbers-in-an-Array/Solution.go
- leetcode/401-500/0421.Maximum-XOR-of-Two-Numbers-in-an-Array/Solution_test.go
Add solution and test-cases for problem 421
> Add solution and test-cases for problem 421

- leetcode/101-200/0117.Populating-Next-Right-Pointers-in-Each-Node-II/Solution.go
- leetcode/101-200/0117.Populating-Next-Right-Pointers-in-Each-Node-II/Solution_test.go
Add solution and test-cases for problem 117
> Add solution and test-cases for problem 117

- leetcode/1901-2000/1903.Largest-Odd-Number-in-String/README.md
- leetcode/1901-2000/1903.Largest-Odd-Number-in-String/Solution.go
- leetcode/1901-2000/1903.Largest-Odd-Number-in-String/Solution_test.go
Add solution and test-cases for problem 1903
> Add solution and test-cases for problem 1903

- leetcode/1701-1800/1716.Calculate-Money-in-Leetcode-Bank/README.md
- leetcode/1701-1800/1716.Calculate-Money-in-Leetcode-Bank/Solution.go
- leetcode/1701-1800/1716.Calculate-Money-in-Leetcode-Bank/Solution_test.go
Add solution and test-cases for problem 1716
> Add solution and test-cases for problem 1716

- leetcode/1601-1700/1688.Count-of-Matches-in-Tournament/README.md
- leetcode/1601-1700/1688.Count-of-Matches-in-Tournament/Solution.go
- leetcode/1601-1700/1688.Count-of-Matches-in-Tournament/Solution_test.go
Add solution and test-cases for problem 1688
> Add solution and test-cases for problem 1688

- leetcode/2201-2300/2264.Largest-3-Same-Digit-Number-in-String/README.md
- leetcode/2201-2300/2264.Largest-3-Same-Digit-Number-in-String/Solution.go
- leetcode/2201-2300/2264.Largest-3-Same-Digit-Number-in-String/Solution_test.go
Add solution and test-cases for problem 2264
> Add solution and test-cases for problem 2264

- leetcode/2001-2100/2044.Count-Number-of-Maximum-Bitwise-OR-Subsets/README.md
- leetcode/2001-2100/2044.Count-Number-of-Maximum-Bitwise-OR-Subsets/Solution.go
- leetcode/2001-2100/2044.Count-Number-of-Maximum-Bitwise-OR-Subsets/Solution_test.go
Add solution and test-cases for problem 2044
> Add solution and test-cases for problem 2044

- leetcode/1601-1700/1685.Sum-of-Absolute-Differences-in-a-Sorted-Array/README.md
- leetcode/1601-1700/1685.Sum-of-Absolute-Differences-in-a-Sorted-Array/Solution.go
- leetcode/1601-1700/1685.Sum-of-Absolute-Differences-in-a-Sorted-Array/Solution_test.go
Add solution and test-cases for problem 1685
> Add solution and test-cases for problem 1685

- leetcode/1601-1700/1630.Arithmetic-Subarrays/README.md
- leetcode/1601-1700/1630.Arithmetic-Subarrays/Solution.go
- leetcode/1601-1700/1630.Arithmetic-Subarrays/Solution_test.go
Add solution and test-cases for problem 1630
> Add solution and test-cases for problem 1630

- leetcode/1801-1900/1814.Count-Nice-Pairs-in-an-Array/README.md
- leetcode/1801-1900/1814.Count-Nice-Pairs-in-an-Array/Solution.go
- leetcode/1801-1900/1814.Count-Nice-Pairs-in-an-Array/Solution_test.go
Add solution and test-cases for problem 1814
> Add solution and test-cases for problem 1814

- leetcode/1801-1900/1887.Reduction-Operations-to-Make-the-Array-Elements-Equal/README.md
- leetcode/1801-1900/1887.Reduction-Operations-to-Make-the-Array-Elements-Equal/Solution.go
- leetcode/1801-1900/1887.Reduction-Operations-to-Make-the-Array-Elements-Equal/Solution_test.go
Add solution and test-cases for problem 1887
> Add solution and test-cases for problem 1887

- leetcode/1801-1900/1838.Frequency-of-the-Most-Frequent-Element/README.md
- leetcode/1801-1900/1838.Frequency-of-the-Most-Frequent-Element/Solution.go
- leetcode/1801-1900/1838.Frequency-of-the-Most-Frequent-Element/Solution_test.go
Add solution and test-cases for problem 1838
> Add solution and test-cases for problem 1838

- leetcode/101-200/0191.Number-of-1-Bits/Solution.go
- leetcode/101-200/0191.Number-of-1-Bits/Solution_test.go
Add solution and test-cases for problem 191
> Add solution and test-cases for problem 191

- leetcode/1901-2000/1980.Find-Unique-Binary-String/README.md
- leetcode/1901-2000/1980.Find-Unique-Binary-String/Solution.go
- leetcode/1901-2000/1980.Find-Unique-Binary-String/Solution_test.go
Add solution and test-cases for problem 1980
> Add solution and test-cases for problem 1980

- leetcode/1801-1900/1846.Maximum-Element-After-Decreasing-and-Rearranging/README.md
- leetcode/1801-1900/1846.Maximum-Element-After-Decreasing-and-Rearranging/Solution.go
- leetcode/1801-1900/1846.Maximum-Element-After-Decreasing-and-Rearranging/Solution_test.go
Add solution and test-cases for problem 1846
> Add solution and test-cases for problem 1846

- leetcode/1901-2000/1930.Unique-Length-3-Palindromic-Subsequences/README.md
- leetcode/1901-2000/1930.Unique-Length-3-Palindromic-Subsequences/Solution.go
- leetcode/1901-2000/1930.Unique-Length-3-Palindromic-Subsequences/Solution_test.go
Add solution and test-cases for problem 1930
> Add solution and test-cases for problem 1930

- leetcode/1901-2000/1913.Maximum-Product-Difference-Between-Two-Pairs/README.md
- leetcode/1901-2000/1913.Maximum-Product-Difference-Between-Two-Pairs/Solution.go
- leetcode/1901-2000/1913.Maximum-Product-Difference-Between-Two-Pairs/Solution_test.go
Add solution and test-cases for problem 1913
> Add solution and test-cases for problem 1913

- leetcode/2701-2800/2706.Buy-Two-Chocolates/README.md
- leetcode/2701-2800/2706.Buy-Two-Chocolates/Solution.go
- leetcode/2701-2800/2706.Buy-Two-Chocolates/Solution_test.go
Add solution and test-cases for problem 2706
> Add solution and test-cases for problem 2706

- leetcode/1401-1500/1442.Count-Triplets-That-Can-Form-Two-Arrays-of-Equal-XOR/README.md
- leetcode/1401-1500/1442.Count-Triplets-That-Can-Form-Two-Arrays-of-Equal-XOR/Solution.go
- leetcode/1401-1500/1442.Count-Triplets-That-Can-Form-Two-Arrays-of-Equal-XOR/Solution_test.go
Add solution and test-cases for problem 1442
> Add solution and test-cases for problem 1442

- leetcode/301-400/0393.UTF-8-Validation/README.md
- leetcode/301-400/0393.UTF-8-Validation/Solution.go
- leetcode/301-400/0393.UTF-8-Validation/Solution_test.go
Add solution and test-cases for problem 393
> Add solution and test-cases for problem 393

- leetcode/401-500/0447.Number-of-Boomerangs/README.md
- leetcode/401-500/0447.Number-of-Boomerangs/Solution.go
- leetcode/401-500/0447.Number-of-Boomerangs/Solution_test.go
Add solution and test-cases for problem 447
> Add solution and test-cases for problem 447

- leetcode/1101-1200/1155.Number-of-Dice-Rolls-With-Target-Sum/README.md
- leetcode/1101-1200/1155.Number-of-Dice-Rolls-With-Target-Sum/Solution.go
- leetcode/1101-1200/1155.Number-of-Dice-Rolls-With-Target-Sum/Solution_test.go
Add solution and test-cases for problem 1155
> Add solution and test-cases for problem 1155

- leetcode/1301-1400/1366.Rank-Teams-by-Votes/README.md
- leetcode/1301-1400/1366.Rank-Teams-by-Votes/Solution.go
- leetcode/1301-1400/1366.Rank-Teams-by-Votes/Solution_test.go
Add solution and test-cases for problem  1366
> Add solution and test-cases for problem  1366

- leetcode/1701-1800/1738.Find-Kth-Largest-XOR-Coordinate-Value/README.md
- leetcode/1701-1800/1738.Find-Kth-Largest-XOR-Coordinate-Value/Solution.go
- leetcode/1701-1800/1738.Find-Kth-Largest-XOR-Coordinate-Value/Solution_test.go
Add solution and test-cases for problem 1738
> Add solution and test-cases for problem 1738

- leetcode/701-800/0721.Accounts-Merge/README.md
- leetcode/701-800/0721.Accounts-Merge/Solution.go
- leetcode/701-800/0721.Accounts-Merge/Solution_test.go
Add solution and test-cases for problem 721
> Add solution and test-cases for problem 721

- leetcode/301-400/0313.Super-Ugly-Number/README.md
- leetcode/301-400/0313.Super-Ugly-Number/Solution.go
- leetcode/301-400/0313.Super-Ugly-Number/Solution_test.go
Add solution and test-cases for problem 313
> Add solution and test-cases for problem 313

- leetcode/1201-1300/1268.Search-Suggestions-System/README.md
- leetcode/1201-1300/1268.Search-Suggestions-System/Solution.go
- leetcode/1201-1300/1268.Search-Suggestions-System/Solution_test.go
Add solution and test-cases for problem 1268
> Add solution and test-cases for problem 1268

- leetcode/1201-1300/1233.Remove-Sub-Folders-from-the-Filesystem/README.md
- leetcode/1201-1300/1233.Remove-Sub-Folders-from-the-Filesystem/Solution.go
- leetcode/1201-1300/1233.Remove-Sub-Folders-from-the-Filesystem/Solution_test.go
Add solution and test-cases for problem 1233
> Add solution and test-cases for problem 1233

- leetcode/2201-2300/2261.K-Divisible-Elements-Subarrays/README.md
- leetcode/2201-2300/2261.K-Divisible-Elements-Subarrays/Solution.go
- leetcode/2201-2300/2261.K-Divisible-Elements-Subarrays/Solution_test.go
Add solution and test-cases for problem 2261
> Add solution and test-cases for problem 2261

- leetcode/1001-1100/1023.Camelcase-Matching/README.md
- leetcode/1001-1100/1023.Camelcase-Matching/Solution.go
- leetcode/1001-1100/1023.Camelcase-Matching/Solution_test.go
Add solution and test-cases for problem 1023
> Add solution and test-cases for problem 1023

- leetcode/301-400/0386.Lexicographical-Numbers/README.md
- leetcode/301-400/0386.Lexicographical-Numbers/Solution.go
- leetcode/301-400/0386.Lexicographical-Numbers/Solution_test.go
Add solution and test-cases for problem 386
> Add solution and test-cases for problem 386

- leetcode/1001-1100/1043.Partition-Array-for-Maximum-Sum/README.md
- leetcode/1001-1100/1043.Partition-Array-for-Maximum-Sum/Solution.go
- leetcode/1001-1100/1043.Partition-Array-for-Maximum-Sum/Solution_test.go
Add solution and test-cases for problem 1043
> Add solution and test-cases for problem 1043

- leetcode/1801-1900/1829.Maximum-XOR-for-Each-Query/README.md
- leetcode/1801-1900/1829.Maximum-XOR-for-Each-Query/Solution.go
- leetcode/1801-1900/1829.Maximum-XOR-for-Each-Query/Solution_test.go
Add solution and test-cases for problem 1829
> Add solution and test-cases for problem 1829

- leetcode/1201-1300/1291.Sequential-Digits/README.md
- leetcode/1201-1300/1291.Sequential-Digits/Solution.go
- leetcode/1201-1300/1291.Sequential-Digits/Solution_test.go
Add solution and test-cases for problem 1291
> Add solution and test-cases for problem 1291

- leetcode/1501-1600/1524.Number-of-Sub-arrays-With-Odd-Sum/README.md
- leetcode/1501-1600/1524.Number-of-Sub-arrays-With-Odd-Sum/Solution.go
- leetcode/1501-1600/1524.Number-of-Sub-arrays-With-Odd-Sum/Solution_test.go
Add solution and test-cases for problem 1524
> Add solution and test-cases for problem 1524

- leetcode/1301-1400/1371.Find-the-Longest-Substring-Containing-Vowels-in-Even-Counts/README.md
- leetcode/1301-1400/1371.Find-the-Longest-Substring-Containing-Vowels-in-Even-Counts/Solution.go
- leetcode/1301-1400/1371.Find-the-Longest-Substring-Containing-Vowels-in-Even-Counts/Solution_test.go
Add solution and test-cases for problem 1371
> Add solution and test-cases for problem 1371

- leetcode/901-1000/0930.Binary-Subarrays-With-Sum/README.md
- leetcode/901-1000/0930.Binary-Subarrays-With-Sum/Solution.go
- leetcode/901-1000/0930.Binary-Subarrays-With-Sum/Solution_test.go
Add solution and test-cases for problem 930
> Add solution and test-cases for problem 930

- leetcode/1701-1800/1785.Minimum-Elements-to-Add-to-Form-a-Given-Sum/README.md
- leetcode/1701-1800/1785.Minimum-Elements-to-Add-to-Form-a-Given-Sum/Solution.go
- leetcode/1701-1800/1785.Minimum-Elements-to-Add-to-Form-a-Given-Sum/Solution_test.go
Add solution and test-cases for problem 1785
> Add solution and test-cases for problem 1785

- leetcode/1001-1100/1004.Max-Consecutive-Ones-III/README.md
- leetcode/1001-1100/1004.Max-Consecutive-Ones-III/Solution.go
- leetcode/1001-1100/1004.Max-Consecutive-Ones-III/Solution_test.go
Add solution and test-cases for problem 1004
> Add solution and test-cases for problem 1004

- leetcode/501-600/0525.Contiguous-Array/README.md
- leetcode/501-600/0525.Contiguous-Array/Solution.go
- leetcode/501-600/0525.Contiguous-Array/Solution_test.go
Add solution and test-cases for problem 525
> Add solution and test-cases for problem 525

- leetcode/601-700/0629.K-Inverse-Pairs-Array/README.md
- leetcode/601-700/0629.K-Inverse-Pairs-Array/Solution.go
- leetcode/601-700/0629.K-Inverse-Pairs-Array/Solution_test.go
Add solution and test-cases for problem 629
> Add solution and test-cases for problem 629

- leetcode/2001-2100/2023.Number-of-Pairs-of-Strings-With-Concatenation-Equal-to-Target/README.md
- leetcode/2001-2100/2023.Number-of-Pairs-of-Strings-With-Concatenation-Equal-to-Target/Solution.go
- leetcode/2001-2100/2023.Number-of-Pairs-of-Strings-With-Concatenation-Equal-to-Target/Solution_test.go
Add solution and test-cases for problem 2023
> Add solution and test-cases for problem 2023

- leetcode/901-1000/0937.Reorder-Data-in-Log-Files/README.md
- leetcode/901-1000/0937.Reorder-Data-in-Log-Files/Solution.go
- leetcode/901-1000/0937.Reorder-Data-in-Log-Files/Solution_test.go
Add solution and test-cases for problem 937
> Add solution and test-cases for problem 937

- leetcode/801-900/0890.Find-and-Replace-Pattern/README.md
- leetcode/801-900/0890.Find-and-Replace-Pattern/Solution.go
- leetcode/801-900/0890.Find-and-Replace-Pattern/Solution_test.go
Add solution and test-cases for problem 890
> Add solution and test-cases for problem 890

- leetcode/401-500/0467.Unique-Substrings-in-Wraparound-String/README.md
- leetcode/401-500/0467.Unique-Substrings-in-Wraparound-String/Solution.go
- leetcode/401-500/0467.Unique-Substrings-in-Wraparound-String/Solution_test.go
Add solution and test-cases for problem 467
> Add solution and test-cases for problem 467

- leetcode/501-600/0522.Longest-Uncommon-Subsequence-II/README.md
- leetcode/501-600/0522.Longest-Uncommon-Subsequence-II/Solution.go
- leetcode/501-600/0522.Longest-Uncommon-Subsequence-II/Solution_test.go
Add solution and test-cases for problem 522
> Add solution and test-cases for problem 522

- leetcode/601-700/0640.Solve-the-Equation/README.md
- leetcode/601-700/0640.Solve-the-Equation/Solution.go
- leetcode/601-700/0640.Solve-the-Equation/Solution_test.go
Add solution and test-cases for problem 640
> Add solution and test-cases for problem 640

- leetcode/501-600/0556.Next-Greater-Element-III/README.md
- leetcode/501-600/0556.Next-Greater-Element-III/Solution.go
- leetcode/501-600/0556.Next-Greater-Element-III/Solution_test.go
Add solution and test-cases for problem 556
> Add solution and test-cases for problem 556

- leetcode/501-600/0537.Complex-Number-Multiplication/README.md
- leetcode/501-600/0537.Complex-Number-Multiplication/Solution.go
- leetcode/501-600/0537.Complex-Number-Multiplication/Solution_test.go
Add solution and test-cases for problem 537
> Add solution and test-cases for problem 537

- leetcode/1801-1900/1818.Minimum-Absolute-Sum-Difference/README.md
- leetcode/1801-1900/1818.Minimum-Absolute-Sum-Difference/Solution.go
- leetcode/1801-1900/1818.Minimum-Absolute-Sum-Difference/Solution_test.go
Add solution and test-cases for problem 1818
> Add solution and test-cases for problem 1818

- leetcode/301-400/0395.Longest-Substring-with-At-Least-K-Repeating-Characters/README.md
- leetcode/301-400/0395.Longest-Substring-with-At-Least-K-Repeating-Characters/Solution.go
- leetcode/301-400/0395.Longest-Substring-with-At-Least-K-Repeating-Characters/Solution_test.go
Add solution and test-cases for problem 395
> Add solution and test-cases for problem 395

- leetcode/1301-1400/1347.Minimum-Number-of-Steps-to-Make-Two-Strings-Anagram/README.md
- leetcode/1301-1400/1347.Minimum-Number-of-Steps-to-Make-Two-Strings-Anagram/Solution.go
- leetcode/1301-1400/1347.Minimum-Number-of-Steps-to-Make-Two-Strings-Anagram/Solution_test.go
Add solution and test-cases for problem 1347
> Add solution and test-cases for problem 1347

- leetcode/801-900/0856.Score-of-Parentheses/README.md
- leetcode/801-900/0856.Score-of-Parentheses/Solution.go
- leetcode/801-900/0856.Score-of-Parentheses/Solution_test.go
Add solution and test-cases for problem 856
> Add solution and test-cases for problem 856

- leetcode/701-800/0784.Letter-Case-Permutation/README.md
- leetcode/701-800/0784.Letter-Case-Permutation/Solution.go
- leetcode/701-800/0784.Letter-Case-Permutation/Solution_test.go
Add solution and test-cases for problem 784
> Add solution and test-cases for problem 784

- leetcode/801-900/0811.Subdomain-Visit-Count/README.md
- leetcode/801-900/0811.Subdomain-Visit-Count/Solution.go
- leetcode/801-900/0811.Subdomain-Visit-Count/Solution_test.go
Add solution and test-cases for problem 811
> Add solution and test-cases for problem 811

- leetcode/601-700/0648.Replace-Words/README.md
- leetcode/601-700/0648.Replace-Words/Solution.go
- leetcode/601-700/0648.Replace-Words/Solution_test.go
Add solution and test-cases for problem 648
> Add solution and test-cases for problem 648

- leetcode/601-700/0677.Map-Sum-Pairs/README.md
- leetcode/601-700/0677.Map-Sum-Pairs/Solution.go
- leetcode/601-700/0677.Map-Sum-Pairs/Solution_test.go
Add solution and test-cases for problem 677
> Add solution and test-cases for problem 677

- leetcode/1801-1900/1897.Redistribute-Characters-to-Make-All-Strings-Equal/README.md
- leetcode/1801-1900/1897.Redistribute-Characters-to-Make-All-Strings-Equal/Solution.go
- leetcode/1801-1900/1897.Redistribute-Characters-to-Make-All-Strings-Equal/Solution_test.go
Add solution and test-cases for problem 1897
> Add solution and test-cases for problem 1897

- leetcode/2301-2400/2350.Shortest-Impossible-Sequence-of-Rolls/README.md
- leetcode/2301-2400/2350.Shortest-Impossible-Sequence-of-Rolls/Solution.go
- leetcode/2301-2400/2350.Shortest-Impossible-Sequence-of-Rolls/Solution_test.go
Add solution and test-cases for problem 2350
> Add solution and test-cases for problem 2350

- leetcode/1601-1700/1624.Largest-Substring-Between-Two-Equal-Characters/README.md
- leetcode/1601-1700/1624.Largest-Substring-Between-Two-Equal-Characters/Solution.go
- leetcode/1601-1700/1624.Largest-Substring-Between-Two-Equal-Characters/Solution_test.go
Add solution and test-cases for problem 1624
> Add solution and test-cases for problem 1624

- leetcode/2601-2700/2610.Convert-an-Array-Into-a-2D-Array-With-Conditions/README.md
- leetcode/2601-2700/2610.Convert-an-Array-Into-a-2D-Array-With-Conditions/Solution.go
- leetcode/2601-2700/2610.Convert-an-Array-Into-a-2D-Array-With-Conditions/Solution_test.go
Add solution and test-cases for problem 2610
> Add solution and test-cases for problem 2610

- leetcode/2801-2900/2870.Minimum-Number-of-Operations-to-Make-Array-Empty/README.md
- leetcode/2801-2900/2870.Minimum-Number-of-Operations-to-Make-Array-Empty/Solution.go
- leetcode/2801-2900/2870.Minimum-Number-of-Operations-to-Make-Array-Empty/Solution_test.go
Add solution and test-cases for problem 2870
> Add solution and test-cases for problem 2870

- leetcode/401-500/0468.Validate-IP-Address/README.md
- leetcode/401-500/0468.Validate-IP-Address/Solution.go
- leetcode/401-500/0468.Validate-IP-Address/Solution_test.go
Add solution and test-cases for problem 468
> Add solution and test-cases for problem 468

- leetcode/2201-2300/2296.Design-a-Text-Editor/README.md
- leetcode/2201-2300/2296.Design-a-Text-Editor/Solution.go
- leetcode/2201-2300/2296.Design-a-Text-Editor/Solution_test.go
Add solution and test-cases for problem 2296
> Add solution and test-cases for problem 2296

- leetcode/1601-1700/1670.Design-Front-Middle-Back-Queue/README.md
- leetcode/1601-1700/1670.Design-Front-Middle-Back-Queue/Solution.go
- leetcode/1601-1700/1670.Design-Front-Middle-Back-Queue/Solution_test.go
Add solution and test-cases for problem 1670
> Add solution and test-cases for problem 1670

- leetcode/401-500/0432.All-O-one-Data-Structure/README.md
- leetcode/401-500/0432.All-O-one-Data-Structure/Solution.go
- leetcode/401-500/0432.All-O-one-Data-Structure/Solution_test.go
Add solution and test-cases for problem 432
> Add solution and test-cases for problem 432

- leetcode/301-400/0372.Super-Pow/README.md
- leetcode/301-400/0372.Super-Pow/Solution.go
- leetcode/301-400/0372.Super-Pow/Solution_test.go
Add solution and test-cases for problem 372
> Add solution and test-cases for problem 372

- leetcode/501-600/0532.K-diff-Pairs-in-an-Array/README.md
- leetcode/501-600/0532.K-diff-Pairs-in-an-Array/Solution.go
- leetcode/501-600/0532.K-diff-Pairs-in-an-Array/Solution_test.go
Add solution and test-cases for problem 532
> Add solution and test-cases for problem 532

- leetcode/201-300/0227.Basic-Calculator-II/README.md
- leetcode/201-300/0227.Basic-Calculator-II/Solution.go
- leetcode/201-300/0227.Basic-Calculator-II/Solution_test.go
Add solution and test-cases for problem 227
> Add solution and test-cases for problem 227

- leetcode/301-400/0365.Water-and-Jug-Problem/README.md
- leetcode/301-400/0365.Water-and-Jug-Problem/Solution.go
- leetcode/301-400/0365.Water-and-Jug-Problem/Solution_test.go
Add solution and test-cases for problem 365
> Add solution and test-cases for problem 365

- leetcode/2501-2600/2540.Minimum-Common-Value/README.md
- leetcode/2501-2600/2540.Minimum-Common-Value/Solution.go
- leetcode/2501-2600/2540.Minimum-Common-Value/Solution_test.go
Add solution and test-cases for problem 2540
> Add solution and test-cases for problem 2540

- leetcode/801-900/0816.Ambiguous-Coordinates/README.md
- leetcode/801-900/0816.Ambiguous-Coordinates/Solution.go
- leetcode/801-900/0816.Ambiguous-Coordinates/Solution_test.go
Add solution and test-cases for problem 816
> Add solution and test-cases for problem 816

- leetcode/701-800/0762.Prime-Number-of-Set-Bits-in-Binary-Representation/README.md
- leetcode/701-800/0762.Prime-Number-of-Set-Bits-in-Binary-Representation/Solution.go
- leetcode/701-800/0762.Prime-Number-of-Set-Bits-in-Binary-Representation/Solution_test.go
Add solution and test-cases for problem 762
> Add solution and test-cases for problem 762

- leetcode/1701-1800/1750.Minimum-Length-of-String-After-Deleting-Similar-Ends/README.md
- leetcode/1701-1800/1750.Minimum-Length-of-String-After-Deleting-Similar-Ends/Solution.go
- leetcode/1701-1800/1750.Minimum-Length-of-String-After-Deleting-Similar-Ends/Solution_test.go
Add solution and test-cases for problem 1750
> Add solution and test-cases for problem 1750

- leetcode/901-1000/0948.Bag-of-Tokens/README.md
- leetcode/901-1000/0948.Bag-of-Tokens/Solution.go
- leetcode/901-1000/0948.Bag-of-Tokens/Solution_test.go
Add solution and test-cases for problem 948
> Add solution and test-cases for problem 948

- leetcode/601-700/0693.Binary-Number-with-Alternating-Bits/README.md
- leetcode/601-700/0693.Binary-Number-with-Alternating-Bits/Solution.go
- leetcode/601-700/0693.Binary-Number-with-Alternating-Bits/Solution_test.go
Add solution and test-cases for problem 693
> Add solution and test-cases for problem 693

- leetcode/601-700/0638.Shopping-Offers/README.md
- leetcode/601-700/0638.Shopping-Offers/Solution.go
- leetcode/601-700/0638.Shopping-Offers/Solution_test.go
Add solution and test-cases for problem 638
> Add solution and test-cases for problem 638

- leetcode/101-200/0190.Reverse-Bits/README.md
- leetcode/101-200/0190.Reverse-Bits/Solution.go
- leetcode/101-200/0190.Reverse-Bits/Solution_test.go
Add solution and test-cases for problem 190
> Add solution and test-cases for problem 190

- leetcode/2401-2500/2424.Longest-Uploaded-Prefix/README.md
- leetcode/2401-2500/2424.Longest-Uploaded-Prefix/Solution.go
- leetcode/2401-2500/2424.Longest-Uploaded-Prefix/Solution_test.go
Add solution and test-cases for problem 2424
> Add solution and test-cases for problem 2424

- leetcode/2801-2900/2864.Maximum-Odd-Binary-Number/README.md
- leetcode/2801-2900/2864.Maximum-Odd-Binary-Number/Solution.go
- leetcode/2801-2900/2864.Maximum-Odd-Binary-Number/Solution_test.go
Add solution and test-cases for problem 2864
> Add solution and test-cases for problem 2864

- leetcode/301-400/0371.Sum-of-Two-Integers/README.md
- leetcode/301-400/0371.Sum-of-Two-Integers/Solution.go
- leetcode/301-400/0371.Sum-of-Two-Integers/Solution_test.go
Add solution and test-cases for problem 371
> Add solution and test-cases for problem 371

- leetcode/601-700/0672.Bulb-Switcher-II/README.md
- leetcode/601-700/0672.Bulb-Switcher-II/Solution.go
- leetcode/601-700/0672.Bulb-Switcher-II/Solution_test.go
Add solution and test-cases for problem 672
> Add solution and test-cases for problem 672

- leetcode/701-800/0786.K-th-Smallest-Prime-Fraction/README.md
- leetcode/701-800/0786.K-th-Smallest-Prime-Fraction/Solution.go
- leetcode/701-800/0786.K-th-Smallest-Prime-Fraction/Solution_test.go
Add solution and test-cases for problem 786
> Add solution and test-cases for problem 786

- leetcode/2701-2800/2709.Greatest-Common-Divisor-Traversal/README.md
- leetcode/2701-2800/2709.Greatest-Common-Divisor-Traversal/Solution.go
- leetcode/2701-2800/2709.Greatest-Common-Divisor-Traversal/Solution_test.go
Add solution and test-cases for problem 2709
> Add solution and test-cases for problem 2709

- leetcode/2001-2100/2092.Find-All-People-With-Secret/README.md
- leetcode/2001-2100/2092.Find-All-People-With-Secret/Solution.go
- leetcode/2001-2100/2092.Find-All-People-With-Secret/Solution_test.go
Add solution and test-cases for problem 2092
> Add solution and test-cases for problem 2092

- leetcode/201-300/0274.H-Index/README.md
- leetcode/201-300/0274.H-Index/Solution.go
- leetcode/201-300/0274.H-Index/Solution_test.go
Add solution and test-cases for problem 274
> Add solution and test-cases for problem 274

- leetcode/1401-1500/1481.Least-Number-of-Unique-Integers-after-K-Removals/README.md
- leetcode/1401-1500/1481.Least-Number-of-Unique-Integers-after-K-Removals/Solution.go
- leetcode/1401-1500/1481.Least-Number-of-Unique-Integers-after-K-Removals/Solution_test.go
Add solution and test-cases for problem 1481
> Add solution and test-cases for problem 1481

- leetcode/2401-2500/2402.Meeting-Rooms-III/README.md
- leetcode/2401-2500/2402.Meeting-Rooms-III/Solution.go
- leetcode/2401-2500/2402.Meeting-Rooms-III/Solution_test.go
Add solution and test-cases for problem 2402
> Add solution and test-cases for problem 2402

- leetcode/1901-2000/1985.Find-the-Kth-Largest-Integer-in-the-Array/README.md
- leetcode/1901-2000/1985.Find-the-Kth-Largest-Integer-in-the-Array/Solution.go
- leetcode/1901-2000/1985.Find-the-Kth-Largest-Integer-in-the-Array/Solution_test.go
Add solution and test-cases for problem 1985
> Add solution and test-cases for problem 1985

- leetcode/2901-3000/2971.Find-Polygon-With-the-Largest-Perimeter/README.md
- leetcode/2901-3000/2971.Find-Polygon-With-the-Largest-Perimeter/Solution.go
- leetcode/2901-3000/2971.Find-Polygon-With-the-Largest-Perimeter/Solution_test.go
Add solution and test-cases for problem 2971
> Add solution and test-cases for problem 2971

- leetcode/901-1000/0945.Minimum-Increment-to-Make-Array-Unique/README.md
- leetcode/901-1000/0945.Minimum-Increment-to-Make-Array-Unique/Solution.go
- leetcode/901-1000/0945.Minimum-Increment-to-Make-Array-Unique/Solution_test.go
Add solution and test-cases for problem 945
> Add solution and test-cases for problem 945

- leetcode/801-900/0869.Reordered-Power-of-2/README.md
- leetcode/801-900/0869.Reordered-Power-of-2/Solution.go
- leetcode/801-900/0869.Reordered-Power-of-2/Solution_test.go
Add solution and test-cases for problem 869
> Add solution and test-cases for problem 869

- leetcode/2101-2200/2108.Find-First-Palindromic-String-in-the-Array/README.md
- leetcode/2101-2200/2108.Find-First-Palindromic-String-in-the-Array/Solution.go
- leetcode/2101-2200/2108.Find-First-Palindromic-String-in-the-Array/Solution_test.go
Add solution and test-cases for problem 2108
> Add solution and test-cases for problem 2108

- leetcode/1001-1100/1090.Largest-Values-From-Labels/README.md
- leetcode/1001-1100/1090.Largest-Values-From-Labels/Solution.go
- leetcode/1001-1100/1090.Largest-Values-From-Labels/Solution_test.go
Add solution and test-cases for problem 1090
> Add solution and test-cases for problem 1090

- leetcode/1001-1100/1079.Letter-Tile-Possibilities/README.md
- leetcode/1001-1100/1079.Letter-Tile-Possibilities/Solution.go
- leetcode/1001-1100/1079.Letter-Tile-Possibilities/Solution_test.go
Add solution and test-cases for problem 1079
> Add solution and test-cases for problem 1079

- leetcode/1301-1400/1352.Product-of-the-Last-K-Numbers/README.md
- leetcode/1301-1400/1352.Product-of-the-Last-K-Numbers/Solution.go
- leetcode/1301-1400/1352.Product-of-the-Last-K-Numbers/Solution_test.go
Add solution and test-cases for problem 1352
> Add solution and test-cases for problem 1352

- leetcode/2401-2500/2486.Append-Characters-to-String-to-Make-Subsequence/README.md
- leetcode/2401-2500/2486.Append-Characters-to-String-to-Make-Subsequence/Solution.go
- leetcode/2401-2500/2486.Append-Characters-to-String-to-Make-Subsequence/Solution_test.go
Add solution and test-cases for problem 2486
> Add solution and test-cases for problem 2486

- leetcode/601-700/0622.Design-Circular-Queue/README.md
- leetcode/601-700/0622.Design-Circular-Queue/Solution.go
- leetcode/601-700/0622.Design-Circular-Queue/Solution_test.go
Add solution and test-cases for problem 622
> Add solution and test-cases for problem 622

- leetcode/1201-1300/1208.Get-Equal-Substrings-Within-Budget/README.md
- leetcode/1201-1300/1208.Get-Equal-Substrings-Within-Budget/Solution.go
- leetcode/1201-1300/1208.Get-Equal-Substrings-Within-Budget/Solution_test.go
Add solution and test-cases for problem 1208
> Add solution and test-cases for problem 1208

- leetcode/501-600/0552.Student-Attendance-Record-II/README.md
- leetcode/501-600/0552.Student-Attendance-Record-II/Solution.go
- leetcode/501-600/0552.Student-Attendance-Record-II/Solution_test.go
Add solution and test-cases for problem 552
> Add solution and test-cases for problem 552

- leetcode/801-900/0900.RLE-Iterator/README.md
- leetcode/801-900/0900.RLE-Iterator/Solution.go
- leetcode/801-900/0900.RLE-Iterator/Solution_test.go
Add solution and test-cases for problem 900
> Add solution and test-cases for problem 900

- leetcode/1701-1800/1781.Sum-of-Beauty-of-All-Substrings/README.md
- leetcode/1701-1800/1781.Sum-of-Beauty-of-All-Substrings/Solution.go
- leetcode/1701-1800/1781.Sum-of-Beauty-of-All-Substrings/Solution_test.go
Add solution and test-cases for problem 1781
> Add solution and test-cases for problem 1781

- leetcode/1801-1900/1863.Sum-of-All-Subset-XOR-Totals/README.md
- leetcode/1801-1900/1863.Sum-of-All-Subset-XOR-Totals/Solution.go
- leetcode/1801-1900/1863.Sum-of-All-Subset-XOR-Totals/Solution_test.go
Add solution and test-cases for problem 1863
> Add solution and test-cases for problem 1863

- leetcode/2401-2500/2491.Divide-Players-Into-Teams-of-Equal-Skill/README.md
- leetcode/2401-2500/2491.Divide-Players-Into-Teams-of-Equal-Skill/Solution.go
- leetcode/2401-2500/2491.Divide-Players-Into-Teams-of-Equal-Skill/Solution_test.go
Add solution and test-cases for problem 2491
> Add solution and test-cases for problem 2491

- leetcode/1501-1600/1553.Minimum-Number-of-Days-to-Eat-N-Oranges/README.md
- leetcode/1501-1600/1553.Minimum-Number-of-Days-to-Eat-N-Oranges/Solution.go
- leetcode/1501-1600/1553.Minimum-Number-of-Days-to-Eat-N-Oranges/Solution_test.go
Add solution and test-cases for problem 1553
> Add solution and test-cases for problem 1553

- leetcode/801-900/0857.Minimum-Cost-to-Hire-K-Workers/README.md
- leetcode/801-900/0857.Minimum-Cost-to-Hire-K-Workers/Solution.go
- leetcode/801-900/0857.Minimum-Cost-to-Hire-K-Workers/Solution_test.go
Add solution and test-cases for problem 857
> Add solution and test-cases for problem 857

- leetcode/1201-1300/1288.Remove-Covered-Intervals/README.md
- leetcode/1201-1300/1288.Remove-Covered-Intervals/Solution.go
- leetcode/1201-1300/1288.Remove-Covered-Intervals/Solution_test.go
Add solution and test-cases for problem 1288
> Add solution and test-cases for problem 1288

- leetcode/501-600/0506.Relative-Ranks/README.md
- leetcode/501-600/0506.Relative-Ranks/Solution.go
- leetcode/501-600/0506.Relative-Ranks/Solution_test.go
Add solution and test-cases for problem 506
> Add solution and test-cases for problem 506

- leetcode/2301-2400/2302.Count-Subarrays-With-Score-Less-Than-K/README.md
- leetcode/2301-2400/2302.Count-Subarrays-With-Score-Less-Than-K/Solution.go
- leetcode/2301-2400/2302.Count-Subarrays-With-Score-Less-Than-K/Solution_test.go
Add solution and test-cases for problem 2302
> Add solution and test-cases for problem 2302

- leetcode/2401-2500/2441.Largest-Positive-Integer-That-Exists-With-Its-Negative/README.md
- leetcode/2401-2500/2441.Largest-Positive-Integer-That-Exists-With-Its-Negative/Solution.go
- leetcode/2401-2500/2441.Largest-Positive-Integer-That-Exists-With-Its-Negative/Solution_test.go
Add solution and test-cases for problem 2441
> Add solution and test-cases for problem 2441

- leetcode/401-500/0410.Split-Array-Largest-Sum/README.md
- leetcode/401-500/0410.Split-Array-Largest-Sum/Solution.go
- leetcode/401-500/0410.Split-Array-Largest-Sum/Solution_test.go
Add solution and test-cases for problem 410
> Add solution and test-cases for problem 410

- leetcode/1501-1600/1542.Find-Longest-Awesome-Substring/README.md
- leetcode/1501-1600/1542.Find-Longest-Awesome-Substring/Solution.go
- leetcode/1501-1600/1542.Find-Longest-Awesome-Substring/Solution_test.go
Add solution and test-cases for problem 1542
> Add solution and test-cases for problem 1542

- leetcode/1901-2000/1915.Number-of-Wonderful-Substrings/README.md
- leetcode/1901-2000/1915.Number-of-Wonderful-Substrings/Solution.go
- leetcode/1901-2000/1915.Number-of-Wonderful-Substrings/Solution_test.go
Add solution and test-cases for problem 1915
> Add solution and test-cases for problem 1915

- leetcode/2901-3000/2997.Minimum-Number-of-Operations-to-Make-Array-XOR-Equal-to-K/README.md
- leetcode/2901-3000/2997.Minimum-Number-of-Operations-to-Make-Array-XOR-Equal-to-K/Solution.go
- leetcode/2901-3000/2997.Minimum-Number-of-Operations-to-Make-Array-XOR-Equal-to-K/Solution_test.go
Add solution and test-cases for problem 2997
> Add solution and test-cases for problem 2997

- leetcode/2301-2400/2370.Longest-Ideal-Subsequence/README.md
- leetcode/2301-2400/2370.Longest-Ideal-Subsequence/Solution.go
- leetcode/2301-2400/2370.Longest-Ideal-Subsequence/Solution_test.go
Add solution and test-cases for problem 2370
> Add solution and test-cases for problem 2370

- leetcode/601-700/0633.Sum-of-Square-Numbers/README.md
- leetcode/601-700/0633.Sum-of-Square-Numbers/Solution.go
- leetcode/601-700/0633.Sum-of-Square-Numbers/Solution_test.go
Add solution and test-cases for problem 633
> Add solution and test-cases for problem 633

- leetcode/701-800/0752.Open-the-Lock/README.md
- leetcode/701-800/0752.Open-the-Lock/Solution.go
- leetcode/701-800/0752.Open-the-Lock/Solution_test.go
Add solution and test-cases for problem 752
> Add solution and test-cases for problem 752

- leetcode/1501-1600/1525.Number-of-Good-Ways-to-Split-a-String/README.md
- leetcode/1501-1600/1525.Number-of-Good-Ways-to-Split-a-String/Solution.go
- leetcode/1501-1600/1525.Number-of-Good-Ways-to-Split-a-String/Solution_test.go
Add solution and test-cases for problem 1525
> Add solution and test-cases for problem 1525

- leetcode/601-700/0650.2-Keys-Keyboard/README.md
- leetcode/601-700/0650.2-Keys-Keyboard/Solution.go
- leetcode/601-700/0650.2-Keys-Keyboard/Solution_test.go
Add solution and test-cases for problem 650
> Add solution and test-cases for problem 650

- leetcode/501-600/0553.Optimal-Division/README.md
- leetcode/501-600/0553.Optimal-Division/Solution.go
- leetcode/501-600/0553.Optimal-Division/Solution_test.go
Add solution and test-cases for problem 553
> Add solution and test-cases for problem 553

- leetcode/501-600/0594.Longest-Harmonious-Subsequence/README.md
- leetcode/501-600/0594.Longest-Harmonious-Subsequence/Solution.go
- leetcode/501-600/0594.Longest-Harmonious-Subsequence/Solution_test.go
Add solution and test-cases for problem 594
> Add solution and test-cases for problem 594

- leetcode/1701-1800/1769.Minimum-Number-of-Operations-to-Move-All-Balls-to-Each-Box/README.md
- leetcode/1701-1800/1769.Minimum-Number-of-Operations-to-Move-All-Balls-to-Each-Box/Solution.go
- leetcode/1701-1800/1769.Minimum-Number-of-Operations-to-Move-All-Balls-to-Each-Box/Solution_test.go
Add solution and test-cases for problem 1769
> Add solution and test-cases for problem 1769

- leetcode/1-100/0090.Subsets-II/README.md
- leetcode/1-100/0090.Subsets-II/Solution.go
- leetcode/1-100/0090.Subsets-II/Solution_test.go
Add solution and test-cases for problem 90
> Add solution and test-cases for problem 90

- leetcode/701-800/0738.Monotone-Increasing-Digits/README.md
- leetcode/701-800/0738.Monotone-Increasing-Digits/Solution.go
- leetcode/701-800/0738.Monotone-Increasing-Digits/Solution_test.go
Add solution and test-cases for problem 738
> Add solution and test-cases for problem 738

- leetcode/401-500/0402.Remove-K-Digits/README.md
- leetcode/401-500/0402.Remove-K-Digits/Solution.go
- leetcode/401-500/0402.Remove-K-Digits/Solution_test.go
Add solution and test-cases for problem 402
> Add solution and test-cases for problem 402

- leetcode/901-1000/0950.Reveal-Cards-In-Increasing-Order/README.md
- leetcode/901-1000/0950.Reveal-Cards-In-Increasing-Order/Solution.go
- leetcode/901-1000/0950.Reveal-Cards-In-Increasing-Order/Solution_test.go
Add solution and test-cases for problem 950
> Add solution and test-cases for problem 950

- leetcode/2001-2100/2073.Time-Needed-to-Buy-Tickets/README.md
- leetcode/2001-2100/2073.Time-Needed-to-Buy-Tickets/Solution.go
- leetcode/2001-2100/2073.Time-Needed-to-Buy-Tickets/Solution_test.go
Add solution and test-cases for problem 2073
> Add solution and test-cases for problem 2073

- leetcode/1201-1300/1249.Minimum-Remove-to-Make-Valid-Parentheses/README.md
- leetcode/1201-1300/1249.Minimum-Remove-to-Make-Valid-Parentheses/Solution.go
- leetcode/1201-1300/1249.Minimum-Remove-to-Make-Valid-Parentheses/Solution_test.go
Add solution and test-cases for problem 1249
> Add solution and test-cases for problem 1249

- leetcode/1201-1300/1296.Divide-Array-in-Sets-of-K-Consecutive-Numbers/README.md
- leetcode/1201-1300/1296.Divide-Array-in-Sets-of-K-Consecutive-Numbers/Solution.go
- leetcode/1201-1300/1296.Divide-Array-in-Sets-of-K-Consecutive-Numbers/Solution_test.go
Add solution and test-cases for problem 1296
> Add solution and test-cases for problem 1296

- leetcode/801-900/0851.Loud-and-Rich/README.md
- leetcode/801-900/0851.Loud-and-Rich/Solution.go
- leetcode/801-900/0851.Loud-and-Rich/Solution_test.go
Add solution and test-cases for problem 851
> Add solution and test-cases for problem 851

- leetcode/1-100/0041.First-Missing-Positive/README.md
- leetcode/1-100/0041.First-Missing-Positive/Solution.go
- leetcode/1-100/0041.First-Missing-Positive/Solution_test.go
Add solution and test-cases for problem 41
> Add solution and test-cases for problem 41

- leetcode/701-800/0713.Subarray-Product-Less-Than-K/README.md
- leetcode/701-800/0713.Subarray-Product-Less-Than-K/Solution.go
- leetcode/701-800/0713.Subarray-Product-Less-Than-K/Solution_test.go
Add solution and test-cases for problem 713
> Add solution and test-cases for problem 713

- leetcode/2901-3000/2962.Count-Subarrays-Where-Max-Element-Appears-at-Least-K-Times/README.md
- leetcode/2901-3000/2962.Count-Subarrays-Where-Max-Element-Appears-at-Least-K-Times/Solution.go
- leetcode/2901-3000/2962.Count-Subarrays-Where-Max-Element-Appears-at-Least-K-Times/Solution_test.go
Add solution and test-cases for problem 2962
> Add solution and test-cases for problem 2962

- leetcode/901-1000/0992.Subarrays-with-K-Different-Integers/README.md
- leetcode/901-1000/0992.Subarrays-with-K-Different-Integers/Solution.go
- leetcode/901-1000/0992.Subarrays-with-K-Different-Integers/Solution_test.go
Add solution and test-cases for problem 992
> Add solution and test-cases for problem 992

- leetcode/1101-1200/1109.Corporate-Flight-Bookings/README.md
- leetcode/1101-1200/1109.Corporate-Flight-Bookings/Solution.go
- leetcode/1101-1200/1109.Corporate-Flight-Bookings/Solution_test.go
Add solution and test-cases for problem 1109
> Add solution and test-cases for problem 1109

- leetcode/701-800/0781.Rabbits-in-Forest/README.md
- leetcode/701-800/0781.Rabbits-in-Forest/Solution.go
- leetcode/701-800/0781.Rabbits-in-Forest/Solution_test.go
Add solution and test-cases for problem 781
> Add solution and test-cases for problem 781

- leetcode/1601-1700/1614.Maximum-Nesting-Depth-of-the-Parentheses/README.md
- leetcode/1601-1700/1614.Maximum-Nesting-Depth-of-the-Parentheses/Solution.go
- leetcode/1601-1700/1614.Maximum-Nesting-Depth-of-the-Parentheses/Solution_test.go
Add solution and test-cases for problem 1614
> Add solution and test-cases for problem 1614

- leetcode/401-500/0448.Find-All-Numbers-Disappeared-in-an-Array/README.md
- leetcode/401-500/0448.Find-All-Numbers-Disappeared-in-an-Array/Solution.go
- leetcode/401-500/0448.Find-All-Numbers-Disappeared-in-an-Array/Solution_test.go
Add solution and test-cases for problem 448
> Add solution and test-cases for problem 448

- leetcode/2301-2400/2396.Strictly-Palindromic-Number/README.md
- leetcode/2301-2400/2396.Strictly-Palindromic-Number/Solution.go
- leetcode/2301-2400/2396.Strictly-Palindromic-Number/Solution_test.go
Add solution and test-cases for problem 2396
> Add solution and test-cases for problem 2396

- leetcode/1001-1100/1051.Height-Checker/README.md
- leetcode/1001-1100/1051.Height-Checker/Solution.go
- leetcode/1001-1100/1051.Height-Checker/Solution_test.go
Add solution and test-cases for problem 1051
> Add solution and test-cases for problem 1051

- leetcode/3001-3100/3005.Count-Elements-With-Maximum-Frequency/README.md
- leetcode/3001-3100/3005.Count-Elements-With-Maximum-Frequency/Solution.go
- leetcode/3001-3100/3005.Count-Elements-With-Maximum-Frequency/Solution_test.go
Add solution and test-cases for problem 3005
> Add solution and test-cases for problem 3005

- leetcode/801-900/0873.Length-of-Longest-Fibonacci-Subsequence/README.md
- leetcode/801-900/0873.Length-of-Longest-Fibonacci-Subsequence/Solution.go
- leetcode/801-900/0873.Length-of-Longest-Fibonacci-Subsequence/Solution_test.go
Add solution and test-cases for problem 873
> Add solution and test-cases for problem 873

- leetcode/1401-1500/1482.Minimum-Number-of-Days-to-Make-m-Bouquets/README.md
- leetcode/1401-1500/1482.Minimum-Number-of-Days-to-Make-m-Bouquets/Solution.go
- leetcode/1401-1500/1482.Minimum-Number-of-Days-to-Make-m-Bouquets/Solution_test.go
Add solution and test-cases for problem 1482
> Add solution and test-cases for problem 1482

- leetcode/801-900/0826.Most-Profit-Assigning-Work/README.md
- leetcode/801-900/0826.Most-Profit-Assigning-Work/Solution.go
- leetcode/801-900/0826.Most-Profit-Assigning-Work/Solution_test.go
Add solution and test-cases for problem 826
> Add solution and test-cases for problem 826

- leetcode/1501-1600/1550.Three-Consecutive-Odds/README.md
- leetcode/1501-1600/1550.Three-Consecutive-Odds/Solution.go
- leetcode/1501-1600/1550.Three-Consecutive-Odds/Solution_test.go
Add solution and test-cases for problem 1550
> Add solution and test-cases for problem 1550

- leetcode/2001-2100/2028.Find-Missing-Observations/README.md
- leetcode/2001-2100/2028.Find-Missing-Observations/Solution.go
- leetcode/2001-2100/2028.Find-Missing-Observations/Solution_test.go
Add solution and test-cases for problem 2028
> Add solution and test-cases for problem 2028

- leetcode/801-900/0874.Walking-Robot-Simulation/README.md
- leetcode/801-900/0874.Walking-Robot-Simulation/Solution.go
- leetcode/801-900/0874.Walking-Robot-Simulation/Solution_test.go
Add solution and test-cases for problem 874
> Add solution and test-cases for problem 874

- leetcode/1901-2000/1945.Sum-of-Digits-of-String-After-Convert/README.md
- leetcode/1901-2000/1945.Sum-of-Digits-of-String-After-Convert/Solution.go
- leetcode/1901-2000/1945.Sum-of-Digits-of-String-After-Convert/Solution_test.go
Add solution and test-cases for problem 1945
> Add solution and test-cases for problem 1945

- leetcode/301-400/0324.Wiggle-Sort-II/README.md
- leetcode/301-400/0324.Wiggle-Sort-II/Solution.go
- leetcode/301-400/0324.Wiggle-Sort-II/Solution_test.go
Add solution and test-cases for problem 324
> Add solution and test-cases for problem 324

- leetcode/1301-1400/1381.Design-a-Stack-With-Increment-Operation/README.md
- leetcode/1301-1400/1381.Design-a-Stack-With-Increment-Operation/Solution.go
- leetcode/1301-1400/1381.Design-a-Stack-With-Increment-Operation/Solution_test.go
Add solution and test-cases for problem 1381
> Add solution and test-cases for problem 1381

- leetcode/1001-1100/1021.Remove-Outermost-Parentheses/README.md
- leetcode/1001-1100/1021.Remove-Outermost-Parentheses/Solution.go
- leetcode/1001-1100/1021.Remove-Outermost-Parentheses/Solution_test.go
Add solution and test-cases for problem 1021
> Add solution and test-cases for problem 1021

- leetcode/1901-2000/1910.Remove-All-Occurrences-of-a-Substring/README.md
- leetcode/1901-2000/1910.Remove-All-Occurrences-of-a-Substring/Solution.go
- leetcode/1901-2000/1910.Remove-All-Occurrences-of-a-Substring/Solution_test.go
Add solution and test-cases for problem 1910
> Add solution and test-cases for problem 1910

- leetcode/1301-1400/1357.Apply-Discount-Every-n-Orders/README.md
- leetcode/1301-1400/1357.Apply-Discount-Every-n-Orders/Solution.go
- leetcode/1301-1400/1357.Apply-Discount-Every-n-Orders/Solution_test.go
Add solution and test-cases for problem 1357
> Add solution and test-cases for problem 1357

- leetcode/901-1000/0981.Time-Based-Key-Value-Store/README.md
- leetcode/901-1000/0981.Time-Based-Key-Value-Store/Solution.go
- leetcode/901-1000/0981.Time-Based-Key-Value-Store/Solution_test.go
Add solution and test-cases for problem 981
> Add solution and test-cases for problem 981

- leetcode/1001-1100/1032.Stream-of-Characters/README.md
- leetcode/1001-1100/1032.Stream-of-Characters/Solution.go
- leetcode/1001-1100/1032.Stream-of-Characters/Solution_test.go
Add solution and test-cases for problem 1032
> Add solution and test-cases for problem 1032

- leetcode/801-900/0819.Most-Common-Word/README.md
- leetcode/801-900/0819.Most-Common-Word/Solution.go
- leetcode/801-900/0819.Most-Common-Word/Solution_test.go
Add solution and test-cases for problem 819
> Add solution and test-cases for problem 819

- leetcode/1001-1100/1014.Best-Sightseeing-Pair/README.md
- leetcode/1001-1100/1014.Best-Sightseeing-Pair/Solution.go
- leetcode/1001-1100/1014.Best-Sightseeing-Pair/Solution_test.go
Add solution and test-cases for problem 1014
> Add solution and test-cases for problem 1014

- leetcode/601-700/0624.Maximum-Distance-in-Arrays/README.md
- leetcode/601-700/0624.Maximum-Distance-in-Arrays/Solution.go
- leetcode/601-700/0624.Maximum-Distance-in-Arrays/Solution_test.go
Add solution and test-cases for problem 624
> Add solution and test-cases for problem 624

- leetcode/701-800/0719.Find-K-th-Smallest-Pair-Distance/README.md
- leetcode/701-800/0719.Find-K-th-Smallest-Pair-Distance/Solution.go
- leetcode/701-800/0719.Find-K-th-Smallest-Pair-Distance/Solution_test.go
Add solution and test-cases for problem 719
> Add solution and test-cases for problem 719

- leetcode/2001-2100/2053.Kth-Distinct-String-in-an-Array/README.md
- leetcode/2001-2100/2053.Kth-Distinct-String-in-an-Array/Solution.go
- leetcode/2001-2100/2053.Kth-Distinct-String-in-an-Array/Solution_test.go
Add solution and test-cases for problem 2053
> Add solution and test-cases for problem 2053

- leetcode/201-300/0282.Expression-Add-Operators/README.md
- leetcode/201-300/0282.Expression-Add-Operators/Solution.go
- leetcode/201-300/0282.Expression-Add-Operators/Solution_test.go
Add solution and test-cases for problem 282
> Add solution and test-cases for problem 282

- leetcode/2101-2200/2134.Minimum-Swaps-to-Group-All-1s-Together-II/README.md
- leetcode/2101-2200/2134.Minimum-Swaps-to-Group-All-1s-Together-II/Solution.go
- leetcode/2101-2200/2134.Minimum-Swaps-to-Group-All-1s-Together-II/Solution_test.go
Add solution and test-cases for problem 2134
> Add solution and test-cases for problem 2134

- leetcode/2601-2700/2678.Number-of-Senior-Citizens/README.md
- leetcode/2601-2700/2678.Number-of-Senior-Citizens/Solution.go
- leetcode/2601-2700/2678.Number-of-Senior-Citizens/Solution_test.go
Add solution and test-cases for problem 2678
> Add solution and test-cases for problem 2678

- leetcode/2901-3000/2976.Minimum-Cost-to-Convert-String-I/README.md
- leetcode/2901-3000/2976.Minimum-Cost-to-Convert-String-I/Solution.go
- leetcode/2901-3000/2976.Minimum-Cost-to-Convert-String-I/Solution_test.go
Add solution and test-cases for problem 2976
> Add solution and test-cases for problem 2976

- leetcode/1401-1500/1451.Rearrange-Words-in-a-Sentence/README.md
- leetcode/1401-1500/1451.Rearrange-Words-in-a-Sentence/Solution.go
- leetcode/1401-1500/1451.Rearrange-Words-in-a-Sentence/Solution_test.go
Add solution and test-cases for problem 1451
> Add solution and test-cases for problem 1451

- leetcode/2101-2200/2191.Sort-the-Jumbled-Numbers/README.md
- leetcode/2101-2200/2191.Sort-the-Jumbled-Numbers/Solution.go
- leetcode/2101-2200/2191.Sort-the-Jumbled-Numbers/Solution_test.go
Add solution and test-cases for problem 2191
> Add solution and test-cases for problem 2191

- leetcode/1601-1700/1636.Sort-Array-by-Increasing-Frequency/README.md
- leetcode/1601-1700/1636.Sort-Array-by-Increasing-Frequency/Solution.go
- leetcode/1601-1700/1636.Sort-Array-by-Increasing-Frequency/Solution_test.go
Add solution and test-cases for problem 1636
> Add solution and test-cases for problem 1636

- leetcode/501-600/0541.Reverse-String-II/README.md
- leetcode/501-600/0541.Reverse-String-II/Solution.go
- leetcode/501-600/0541.Reverse-String-II/Solution_test.go
Add solution and test-cases for problem 541
> Add solution and test-cases for problem 541

- leetcode/1401-1500/1475.Final-Prices-With-a-Special-Discount-in-a-Shop/README.md
- leetcode/1401-1500/1475.Final-Prices-With-a-Special-Discount-in-a-Shop/Solution.go
- leetcode/1401-1500/1475.Final-Prices-With-a-Special-Discount-in-a-Shop/Solution_test.go
Add solution and test-cases for problem 1475
> Add solution and test-cases for problem 1475

- leetcode/1601-1700/1679.Max-Number-of-K-Sum-Pairs/README.md
- leetcode/1601-1700/1679.Max-Number-of-K-Sum-Pairs/Solution.go
- leetcode/1601-1700/1679.Max-Number-of-K-Sum-Pairs/Solution_test.go
Add solution and test-cases for problem 1679
> Add solution and test-cases for problem 1679

- leetcode/2501-2600/2582.Pass-the-Pillow/README.md
- leetcode/2501-2600/2582.Pass-the-Pillow/Solution.go
- leetcode/2501-2600/2582.Pass-the-Pillow/Solution_test.go
Add solution and test-cases for problem 2582
> Add solution and test-cases for problem 2582

- leetcode/601-700/0670.Maximum-Swap/README.md
- leetcode/601-700/0670.Maximum-Swap/Solution.go
- leetcode/601-700/0670.Maximum-Swap/Solution_test.go
Add solution and test-cases for problem 670
> Add solution and test-cases for problem 670

- leetcode/1601-1700/1684.Count-the-Number-of-Consistent-Strings/README.md
- leetcode/1601-1700/1684.Count-the-Number-of-Consistent-Strings/Solution.go
- leetcode/1601-1700/1684.Count-the-Number-of-Consistent-Strings/Solution_test.go
Add solution and test-cases for problem 1684
> Add solution and test-cases for problem 1684

- leetcode/2201-2300/2220.Minimum-Bit-Flips-to-Convert-Number/README.md
- leetcode/2201-2300/2220.Minimum-Bit-Flips-to-Convert-Number/Solution.go
- leetcode/2201-2300/2220.Minimum-Bit-Flips-to-Convert-Number/Solution_test.go
Add solution and test-cases for problem 2220
> Add solution and test-cases for problem 2220

- leetcode/2401-2500/2419.Longest-Subarray-With-Maximum-Bitwise-AND/README.md
- leetcode/2401-2500/2419.Longest-Subarray-With-Maximum-Bitwise-AND/Solution.go
- leetcode/2401-2500/2419.Longest-Subarray-With-Maximum-Bitwise-AND/Solution_test.go
Add solution and test-cases for problem 2419
> Add solution and test-cases for problem 2419

- leetcode/2301-2400/2343.Query-Kth-Smallest-Trimmed-Number/README.md
- leetcode/2301-2400/2343.Query-Kth-Smallest-Trimmed-Number/Solution.go
- leetcode/2301-2400/2343.Query-Kth-Smallest-Trimmed-Number/Solution_test.go
Add solution and test-cases for problem 2343
> Add solution and test-cases for problem 2343

- leetcode/2901-3000/2947.Count-Beautiful-Substrings-I/README.md
- leetcode/2901-3000/2947.Count-Beautiful-Substrings-I/Solution.go
- leetcode/2901-3000/2947.Count-Beautiful-Substrings-I/Solution_test.go
Add solution and test-cases for problem 2947
> Add solution and test-cases for problem 2947

- leetcode/1501-1600/1545.Find-Kth-Bit-in-Nth-Binary-String/README.md
- leetcode/1501-1600/1545.Find-Kth-Bit-in-Nth-Binary-String/Solution.go
- leetcode/1501-1600/1545.Find-Kth-Bit-in-Nth-Binary-String/Solution_test.go
Add solution and test-cases for problem 1545
> Add solution and test-cases for problem 1545

- leetcode/2201-2300/2275.Largest-Combination-With-Bitwise-AND-Greater-Than-Zero/README.md
- leetcode/2201-2300/2275.Largest-Combination-With-Bitwise-AND-Greater-Than-Zero/Solution.go
- leetcode/2201-2300/2275.Largest-Combination-With-Bitwise-AND-Greater-Than-Zero/Solution_test.go
Add solution and test-cases for problem 2275
> Add solution and test-cases for problem 2275

- leetcode/1801-1900/1859.Sorting-the-Sentence/README.md
- leetcode/1801-1900/1859.Sorting-the-Sentence/Solution.go
- leetcode/1801-1900/1859.Sorting-the-Sentence/Solution_test.go
Add solution and test-cases for problem 1859
> Add solution and test-cases for problem 1859

- leetcode/1901-2000/1942.The-Number-of-the-Smallest-Unoccupied-Chair/README.md
- leetcode/1901-2000/1942.The-Number-of-the-Smallest-Unoccupied-Chair/Solution.go
- leetcode/1901-2000/1942.The-Number-of-the-Smallest-Unoccupied-Chair/Solution_test.go
Add solution and test-cases for problem 1942
> Add solution and test-cases for problem 1942

- leetcode/2401-2500/2491.Divide-Players-Into-Teams-of-Equal-Skill/Solution.go
- leetcode/2401-2500/2491.Divide-Players-Into-Teams-of-Equal-Skill/Solution_test.go
> Add solution for problem 2491

- leetcode/1501-1600/1590.Make-Sum-Divisible-by-P/README.md
- leetcode/1501-1600/1590.Make-Sum-Divisible-by-P/Solution.go
- leetcode/1501-1600/1590.Make-Sum-Divisible-by-P/Solution_test.go
Add solution and test-cases for problem 1590
> Add solution and test-cases for problem 1590

- leetcode/1401-1500/1497.Check-If-Array-Pairs-Are-Divisible-by-k/README.md
- leetcode/1401-1500/1497.Check-If-Array-Pairs-Are-Divisible-by-k/Solution.go
- leetcode/1401-1500/1497.Check-If-Array-Pairs-Are-Divisible-by-k/Solution_test.go
Add solution and test-cases for problem 1497
> Add solution and test-cases for problem 1497

- leetcode/1001-1100/1041.Robot-Bounded-In-Circle/README.md
- leetcode/1001-1100/1041.Robot-Bounded-In-Circle/Solution.go
- leetcode/1001-1100/1041.Robot-Bounded-In-Circle/Solution_test.go
Add solution and test-cases for problem 1041
> Add solution and test-cases for problem 1041

- leetcode/301-400/0400.Nth-Digit/README.md
- leetcode/301-400/0400.Nth-Digit/Solution.go
- leetcode/301-400/0400.Nth-Digit/Solution_test.go
Add solution and test-cases for problem 400
> Add solution and test-cases for problem 400

- leetcode/1001-1100/1078.Occurrences-After-Bigram/README.md
- leetcode/1001-1100/1078.Occurrences-After-Bigram/Solution.go
- leetcode/1001-1100/1078.Occurrences-After-Bigram/Solution_test.go
Add solution and test-cases for problem 1078
> Add solution and test-cases for problem 1078

- leetcode/3201-3300/3254.Find-the-Power-of-K-Size-Subarrays-I/README.md
- leetcode/3201-3300/3254.Find-the-Power-of-K-Size-Subarrays-I/Solution.go
- leetcode/3201-3300/3254.Find-the-Power-of-K-Size-Subarrays-I/Solution_test.go
Add solution and test-cases for problem 3254
> Add solution and test-cases for problem 3254

- leetcode/1501-1600/1574.Shortest-Subarray-to-be-Removed-to-Make-Array-Sorted/README.md
- leetcode/1501-1600/1574.Shortest-Subarray-to-be-Removed-to-Make-Array-Sorted/Solution.go
- leetcode/1501-1600/1574.Shortest-Subarray-to-be-Removed-to-Make-Array-Sorted/Solution_test.go
Add solution and test-cases for problem 1574
> Add solution and test-cases for problem 1574

- leetcode/2001-2100/2064.Minimized-Maximum-of-Products-Distributed-to-Any-Store/README.md
- leetcode/2001-2100/2064.Minimized-Maximum-of-Products-Distributed-to-Any-Store/Solution.go
- leetcode/2001-2100/2064.Minimized-Maximum-of-Products-Distributed-to-Any-Store/Solution_test.go
Add solution and test-cases for problem 2064
> Add solution and test-cases for problem 2064

- leetcode/2601-2700/2601.Prime-Subtraction-Operation/README.md
- leetcode/2601-2700/2601.Prime-Subtraction-Operation/Solution.go
- leetcode/2601-2700/2601.Prime-Subtraction-Operation/Solution_test.go
Add solution and test-cases for problem 2601
> Add solution and test-cases for problem 2601

- leetcode/3001-3100/3097.Shortest-Subarray-With-OR-at-Least-K-II/README.md
- leetcode/3001-3100/3097.Shortest-Subarray-With-OR-at-Least-K-II/Solution.go
- leetcode/3001-3100/3097.Shortest-Subarray-With-OR-at-Least-K-II/Solution_test.go
Add solution and test-cases for problem 3097
> Add solution and test-cases for problem 3097

- leetcode/3101-3200/3133.Minimum-Array-End/README.md
- leetcode/3101-3200/3133.Minimum-Array-End/Solution.go
- leetcode/3101-3200/3133.Minimum-Array-End/Solution_test.go
Add solution and test-cases for problem 3133
> Add solution and test-cases for problem 3133

- leetcode/3001-3100/3011.Find-if-Array-Can-Be-Sorted/README.md
- leetcode/3001-3100/3011.Find-if-Array-Can-Be-Sorted/Solution.go
- leetcode/3001-3100/3011.Find-if-Array-Can-Be-Sorted/Solution_test.go
Add solution and test-cases for problem 3011
> Add solution and test-cases for problem 3011

- leetcode/901-1000/0923.3Sum-With-Multiplicity/README.md
- leetcode/901-1000/0923.3Sum-With-Multiplicity/Solution.go
- leetcode/901-1000/0923.3Sum-With-Multiplicity/Solution_test.go
Add solution and test-cases for problem 923
> Add solution and test-cases for problem 923

- leetcode/2901-3000/2940.Find-Building-Where-Alice-and-Bob-Can-Meet/README.md
- leetcode/2901-3000/2940.Find-Building-Where-Alice-and-Bob-Can-Meet/Solution.go
- leetcode/2901-3000/2940.Find-Building-Where-Alice-and-Bob-Can-Meet/Solution_test.go
Add solution and test-cases for problem 2940
> Add solution and test-cases for problem 2940

- leetcode/2001-2100/2099.Find-Subsequence-of-Length-K-With-the-Largest-Sum/README.md
- leetcode/2001-2100/2099.Find-Subsequence-of-Length-K-With-the-Largest-Sum/Solution.go
- leetcode/2001-2100/2099.Find-Subsequence-of-Length-K-With-the-Largest-Sum/Solution_test.go
Add solution and test-cases for problem 2099
> Add solution and test-cases for problem 2099

- leetcode/3201-3300/3264.Final-Array-State-After-K-Multiplication-Operations-I/README.md
- leetcode/3201-3300/3264.Final-Array-State-After-K-Multiplication-Operations-I/Solution.go
- leetcode/3201-3300/3264.Final-Array-State-After-K-Multiplication-Operations-I/Solution_test.go
Add solution and test-cases for problem 3264
> Add solution and test-cases for problem 3264

- leetcode/2901-3000/2982.Find-Longest-Special-Substring-That-Occurs-Thrice-II/README.md
- leetcode/2901-3000/2982.Find-Longest-Special-Substring-That-Occurs-Thrice-II/Solution.go
- leetcode/2901-3000/2982.Find-Longest-Special-Substring-That-Occurs-Thrice-II/Solution_test.go
Add solution and test-cases for problem 2982
> Add solution and test-cases for problem 2982

- leetcode/2901-3000/2981.Find-Longest-Special-Substring-That-Occurs-Thrice-I/README.md
- leetcode/2901-3000/2981.Find-Longest-Special-Substring-That-Occurs-Thrice-I/Solution.go
- leetcode/2901-3000/2981.Find-Longest-Special-Substring-That-Occurs-Thrice-I/Solution_test.go
Add solution and test-cases for problem 2981
> Add solution and test-cases for problem 2981

- leetcode/1701-1800/1760.Minimum-Limit-of-Balls-in-a-Bag/README.md
- leetcode/1701-1800/1760.Minimum-Limit-of-Balls-in-a-Bag/Solution.go
- leetcode/1701-1800/1760.Minimum-Limit-of-Balls-in-a-Bag/Solution_test.go
Add solution and test-cases for problem 1760
> Add solution and test-cases for problem 1760

- leetcode/2301-2400/2337.Move-Pieces-to-Obtain-a-String/README.md
- leetcode/2301-2400/2337.Move-Pieces-to-Obtain-a-String/Solution.go
- leetcode/2301-2400/2337.Move-Pieces-to-Obtain-a-String/Solution_test.go
Add solution and test-cases for problem 2337
> Add solution and test-cases for problem 2337

- leetcode/1301-1400/1324.Print-Words-Vertically/README.md
- leetcode/1301-1400/1324.Print-Words-Vertically/Solution.go
- leetcode/1301-1400/1324.Print-Words-Vertically/Solution_test.go
Add solution and test-cases for problem 1324
> Add solution and test-cases for problem 1324

- leetcode/2401-2500/2461.Maximum-Sum-of-Distinct-Subarrays-With-Length-K/README.md
- leetcode/2401-2500/2461.Maximum-Sum-of-Distinct-Subarrays-With-Length-K/Solution.go
- leetcode/2401-2500/2461.Maximum-Sum-of-Distinct-Subarrays-With-Length-K/Solution_test.go
Add solution and test-cases for problem 2461
> Add solution and test-cases for problem 2461

- leetcode/1301-1400/1375.Number-of-Times-Binary-String-Is-Prefix-Aligned/README.md
- leetcode/1301-1400/1375.Number-of-Times-Binary-String-Is-Prefix-Aligned/Solution.go
- leetcode/1301-1400/1375.Number-of-Times-Binary-String-Is-Prefix-Aligned/Solution_test.go
Add solution and test-cases for problem 1375
> Add solution and test-cases for problem 1375

- leetcode/2101-2200/2161.Partition-Array-According-to-Given-Pivot/README.md
- leetcode/2101-2200/2161.Partition-Array-According-to-Given-Pivot/Solution.go
- leetcode/2101-2200/2161.Partition-Array-According-to-Given-Pivot/Solution_test.go
Add solution and test-cases for problem 2161
> Add solution and test-cases for problem 2161

- leetcode/1701-1800/1718.Construct-the-Lexicographically-Largest-Valid-Sequence/README.md
- leetcode/1701-1800/1718.Construct-the-Lexicographically-Largest-Valid-Sequence/Solution.go
- leetcode/1701-1800/1718.Construct-the-Lexicographically-Largest-Valid-Sequence/Solution_test.go
Add solution and test-cases for problem  1718
> Add solution and test-cases for problem  1718

- leetcode/2301-2400/2342.Max-Sum-of-a-Pair-With-Equal-Sum-of-Digits/README.md
- leetcode/2301-2400/2342.Max-Sum-of-a-Pair-With-Equal-Sum-of-Digits/Solution.go
- leetcode/2301-2400/2342.Max-Sum-of-a-Pair-With-Equal-Sum-of-Digits/Solution_test.go
Add solution and test-cases for problem 2342
> Add solution and test-cases for problem 2342

- leetcode/1701-1800/1790.Check-if-One-String-Swap-Can-Make-Strings-Equal/README.md
- leetcode/1701-1800/1790.Check-if-One-String-Swap-Can-Make-Strings-Equal/Solution.go
- leetcode/1701-1800/1790.Check-if-One-String-Swap-Can-Make-Strings-Equal/Solution_test.go
Add solution and test-cases for problem 1790
> Add solution and test-cases for problem 1790

- leetcode/701-800/0728.Self-Dividing-Numbers/README.md
- leetcode/701-800/0728.Self-Dividing-Numbers/Solution.go
- leetcode/701-800/0728.Self-Dividing-Numbers/Solution_test.go
Add solution and test-cases for problem 728
> Add solution and test-cases for problem 728

- leetcode/401-500/0493.Reverse-Pairs/README.md
- leetcode/401-500/0493.Reverse-Pairs/Solution.go
- leetcode/401-500/0493.Reverse-Pairs/Solution_test.go
Add solution and test-cases for problem 493
> Add solution and test-cases for problem 493

- leetcode/2401-2500/2425.Bitwise-XOR-of-All-Pairings/README.md
- leetcode/2401-2500/2425.Bitwise-XOR-of-All-Pairings/Solution.go
- leetcode/2401-2500/2425.Bitwise-XOR-of-All-Pairings/Solution_test.go
Add solution and test-cases for problem 2425
> Add solution and test-cases for problem 2425

- leetcode/1301-1400/1400.Construct-K-Palindrome-Strings/README.md
- leetcode/1301-1400/1400.Construct-K-Palindrome-Strings/Solution.go
- leetcode/1301-1400/1400.Construct-K-Palindrome-Strings/Solution_test.go
Add solution and test-cases for problem 1400
> Add solution and test-cases for problem 1400

- leetcode/3101-3200/3115.Maximum-Prime-Difference/README.md
- leetcode/3101-3200/3115.Maximum-Prime-Difference/Solution.go
- leetcode/3101-3200/3115.Maximum-Prime-Difference/Solution_test.go
Add solution and test-cases for problem 3115
> Add solution and test-cases for problem 3115
